// src/features/recordings/topics.data.js
//
// Static topics, tagged by category — spinning happens entirely
// client-side. Backend just receives whichever `text` string is picked
// as `topic` on recording creation, nothing category-related is sent.

export const CATEGORIES = [
  'Technology',
  'Business',
  'Education',
  'Culture',
  'Sports',
  'Philosophy',
  'Politics',
  'Health',
  'Environment',
];

export const TOPICS = [
  // Technology
  { text: 'AI will replace most software engineers within ten years.', category: 'Technology' },
  { text: 'Smartphones have made us less social, not more.', category: 'Technology' },
  { text: "Self-driving cars should be the norm once they're proven safer than humans.", category: 'Technology' },
  { text: 'Tech companies should be banned from selling personal data.', category: 'Technology' },
  { text: 'Cryptocurrency will eventually replace traditional money.', category: 'Technology' },
  { text: 'Children under thirteen should not be allowed on social media.', category: 'Technology' },
  { text: 'Algorithms shape your opinions more than your friends do.', category: 'Technology' },
  { text: 'Open source software has done more for humanity than any tech company.', category: 'Technology' },
  { text: 'Smart speakers in the home are a privacy disaster waiting to happen.', category: 'Technology' },
  { text: 'VR will eventually replace most travel.', category: 'Technology' },
  { text: 'Coding should be a required class in high school.', category: 'Technology' },
  { text: 'All bot accounts should be banned from social media.', category: 'Technology' },
  { text: 'The internet was better before algorithms took over social media.', category: 'Technology' },
  { text: 'Apps should be required to ship with a delete-my-data button.', category: 'Technology' },
  { text: 'Facial recognition in public spaces should be banned.', category: 'Technology' },
  { text: 'Recording people using smart glasses in public spaces should be banned.', category: 'Technology' },
  { text: 'Big tech companies are more powerful than most governments.', category: 'Technology' },
  { text: 'The smartphone has done more harm to teenagers than alcohol.', category: 'Technology' },
  { text: 'Wearable health trackers do more harm than good.', category: 'Technology' },
  { text: 'Passwords will be obsolete within the next decade.', category: 'Technology' },
  { text: 'Everyone should use a password manager.', category: 'Technology' },
  { text: 'Video calls have made people worse at reading body language.', category: 'Technology' },
  { text: 'E-books are better than physical books for retention.', category: 'Technology' },
  { text: 'AI-generated art should be clearly labeled as AI-made.', category: 'Technology' },
  { text: 'Right-to-repair laws should require manufacturers to sell spare parts to consumers.', category: 'Technology' },
  { text: 'Autonomous delivery drones will be commonplace within ten years.', category: 'Technology' },
  { text: 'Online anonymity does more good than harm.', category: 'Technology' },
  { text: 'Robots will eventually make better caregivers for the elderly than humans.', category: 'Technology' },
  { text: 'Every website should be required to offer a version that doesn\'t track visitors.', category: 'Technology' },
  { text: 'The next major computing platform will be wearable, not mobile.', category: 'Technology' },
  { text: 'Chatbots should be required to disclose that they are not human.', category: 'Technology' },
  { text: '3D printing will disrupt manufacturing more than the internet disrupted media.', category: 'Technology' },
  { text: 'Biometric login is safer than passwords.', category: 'Technology' },
  { text: 'AI coding assistants will make traditional computer science degrees less valuable.', category: 'Technology' },
  { text: 'Space exploration should be led by private companies, not governments.', category: 'Technology' },
  { text: 'The metaverse will never replace real-world socializing.', category: 'Technology' },
  { text: 'Encrypted messaging apps should never include a government backdoor.', category: 'Technology' },
  { text: 'Most people would be happier using a basic phone instead of a smartphone.', category: 'Technology' },
  { text: 'AI companions will become a normal part of romantic life within a generation.', category: 'Technology' },
  { text: 'Companies should be required to compensate users automatically after a data breach.', category: 'Technology' },
  { text: 'Digital minimalism is a trend that won\'t last.', category: 'Technology' },
  { text: 'Legal screen-time limits on kids\' devices would work better than relying on parents alone.', category: 'Technology' },
  { text: 'Cloud storage has made people careless about backing up their own data.', category: 'Technology' },
  { text: 'Deepfakes will make video evidence unreliable in court within ten years.', category: 'Technology' },
  { text: 'Every smart home device should have a physical off switch for its microphone.', category: 'Technology' },

  // Business
  { text: 'Remote work is more productive than working in an office.', category: 'Business' },
  { text: 'Companies should be required to publish every employee\'s salary.', category: 'Business' },
  { text: 'The four-day work week should be the new standard.', category: 'Business' },
  { text: 'There are no ethical billionaires.', category: 'Business' },
  { text: 'Unpaid internships should not exist.', category: 'Business' },
  { text: 'Every big decision by a public company should be put up to a vote by shareholders.', category: 'Business' },
  { text: 'The gig economy is a step backward for labour rights.', category: 'Business' },
  { text: 'Branding has become more important than the product itself.', category: 'Business' },
  { text: 'Customer service has gotten worse in every industry over the past decade.', category: 'Business' },
  { text: 'Inheritances above a certain high threshold should face much heavier taxes.', category: 'Business' },
  { text: 'Everyone should retire at 60–65.', category: 'Business' },
  { text: 'Tipping culture has spiraled out of control.', category: 'Business' },
  { text: 'Performance reviews are a waste of time.', category: 'Business' },
  { text: 'Office dress codes are pointless in the modern era.', category: 'Business' },
  { text: 'Patents stifle innovation more than they protect it.', category: 'Business' },
  { text: 'Every job posting should be required to list its salary range.', category: 'Business' },
  { text: 'Layoffs delivered by video call or email should be illegal.', category: 'Business' },
  { text: 'Non-compete agreements should be banned.', category: 'Business' },
  { text: 'Startups fail more often from bad co-founders than bad ideas.', category: 'Business' },
  { text: 'Open-plan offices hurt productivity more than they help collaboration.', category: 'Business' },
  { text: 'Employees should be able to unionize without employer interference.', category: 'Business' },
  { text: 'A college degree should not be required for most entry-level jobs.', category: 'Business' },
  { text: 'Every company should offer more flexible leave policies.', category: 'Business' },
  { text: 'The traditional 9-to-5 workday no longer makes sense.', category: 'Business' },
  { text: 'Severance pay should be required by law after layoffs.', category: 'Business' },
  { text: 'Business ethics classes make little difference in how executives actually behave.', category: 'Business' },
  { text: 'Franchising is a better path to wealth than starting an original business.', category: 'Business' },
  { text: 'Middle management is mostly unnecessary overhead.', category: 'Business' },
  { text: 'Shareholders care too much about quarterly profits and too little about long-term growth.', category: 'Business' },
  { text: 'Small businesses deserve more tax breaks than large corporations.', category: 'Business' },
  { text: 'Job-hopping is the fastest way to grow your salary.', category: 'Business' },
  { text: 'Company loyalty is a myth that only benefits employers.', category: 'Business' },
  { text: 'Mentorship matters more than raw talent for career success.', category: 'Business' },
  { text: 'Return-to-office mandates are more about control than productivity.', category: 'Business' },
  { text: 'AI will create more jobs than it destroys.', category: 'Business' },
  { text: 'Meetings that could be an email are a bigger problem than most companies admit.', category: 'Business' },
  { text: 'Salary negotiation should be taught in every college.', category: 'Business' },
  { text: 'Employee stock options are overrated as compensation.', category: 'Business' },
  { text: 'Family businesses are harder to scale than founder-led startups.', category: 'Business' },
  { text: 'Networking matters more than credentials when it comes to getting hired.', category: 'Business' },
  { text: 'Businesses should be required to publicly disclose their environmental impact.', category: 'Business' },
  { text: 'Great leaders are made, not born.', category: 'Business' },

  // Education
  { text: 'AI tutors will be better than human teachers within five years.', category: 'Education' },
  { text: 'College is the best path to success.', category: 'Education' },
  { text: 'Standardized testing is not a great way to assess a student\'s capabilities.', category: 'Education' },
  { text: 'Schools should be required to teach financial literacy.', category: 'Education' },
  { text: 'Students should be allowed to use AI while doing homework.', category: 'Education' },
  { text: 'Every student should learn how to cook before they graduate high school.', category: 'Education' },
  { text: 'Public schools should be funded more equally regardless of location.', category: 'Education' },
  { text: 'Every student should learn a second language fluently before graduating.', category: 'Education' },
  { text: 'Recess / outdoor play should be mandatory at every grade level.', category: 'Education' },
  { text: 'Teachers should be paid much more.', category: 'Education' },
  { text: 'Online learning has made students worse, not better.', category: 'Education' },
  { text: 'Required reading lists should include far more diverse voices.', category: 'Education' },
  { text: 'Mandatory school uniforms make students more equal, not less.', category: 'Education' },
  { text: 'Final exams measure memorization, not understanding.', category: 'Education' },
  { text: 'Grades do more harm than good to student motivation.', category: 'Education' },
  { text: 'Every school should offer mental health classes.', category: 'Education' },
  { text: 'Vocational / skill-based education should be marketed as equally valuable as a four-year degree.', category: 'Education' },
  { text: 'Class sizes should be capped at a reasonable number.', category: 'Education' },
  { text: 'Homework should be optional in primary school.', category: 'Education' },
  { text: 'Every student should take a public speaking class before graduating.', category: 'Education' },
  { text: 'School should start later in the day for teenagers.', category: 'Education' },
  { text: 'Cursive / handwriting skills still matter and should be taught.', category: 'Education' },
  { text: 'Group projects do more to hurt learning than help it.', category: 'Education' },
  { text: 'Attendance policies are more about compliance than actual learning.', category: 'Education' },
  { text: 'Gifted programs do more harm than good by separating students too early.', category: 'Education' },
  { text: 'Letter grades should be replaced with detailed written feedback.', category: 'Education' },
  { text: 'Every student should learn to type properly before middle school.', category: 'Education' },
  { text: 'School sports should not require a minimum GPA to participate.', category: 'Education' },
  { text: 'Teachers should be allowed to fail students for excessive absences alone.', category: 'Education' },
  { text: 'Field trips are one of the most underrated parts of education.', category: 'Education' },
  { text: 'Every school should teach media literacy as its own subject.', category: 'Education' },
  { text: 'Elite universities admit too many students based on legacy or connections.', category: 'Education' },
  { text: 'Year-round schooling would benefit students more than long summer breaks.', category: 'Education' },
  { text: 'Students should be graded on effort as much as results.', category: 'Education' },
  { text: 'Parents should have less influence over school curriculum decisions.', category: 'Education' },
  { text: 'Learning a musical instrument should be encouraged more strongly in school.', category: 'Education' },
  { text: 'Vocational skills should be taught alongside academics starting in middle school.', category: 'Education' },
  { text: 'Class rank does more to discourage students than motivate them.', category: 'Education' },
  { text: 'Every student should complete a community service project before graduating.', category: 'Education' },
  { text: 'Study abroad or exchange programs should be more accessible, not just for the wealthy.', category: 'Education' },

  // Culture
  { text: 'Cancel culture has gone too far.', category: 'Culture' },
  { text: 'Tipping should be abolished and replaced with higher wages.', category: 'Culture' },
  { text: 'Reality TV has done more harm than good for society.', category: 'Culture' },
  { text: 'Streaming services killed the magic of going to the movies / cinema.', category: 'Culture' },
  { text: 'Dating apps have made romance worse.', category: 'Culture' },
  { text: 'Pop music today is worse than it was twenty years ago.', category: 'Culture' },
  { text: 'Sequels, remakes and reboots prove the industry is out of ideas.', category: 'Culture' },
  { text: 'Influencer marketing has destroyed authentic recommendation.', category: 'Culture' },
  { text: 'Tattoos have lost their edge now that everyone has them.', category: 'Culture' },
  { text: 'Public libraries are the most underrated institution in society.', category: 'Culture' },
  { text: 'Modern architecture is often uglier than what it replaced.', category: 'Culture' },
  { text: 'Award shows are no longer culturally relevant.', category: 'Culture' },
  { text: 'Memes have replaced traditional satire as cultural commentary.', category: 'Culture' },
  { text: 'Reading fiction is just as valuable as reading non-fiction.', category: 'Culture' },
  { text: 'Live concerts and events are not worth the price anymore.', category: 'Culture' },
  { text: 'Podcasts have replaced books for many adults.', category: 'Culture' },
  { text: 'A lot of modern art is more hype than substance.', category: 'Culture' },
  { text: 'Short-form video is rotting attention spans across all generations.', category: 'Culture' },
  { text: 'Every adult should travel solo at least once.', category: 'Culture' },
  { text: 'Marriage as an institution is changing faster than people admit.', category: 'Culture' },
  { text: 'Nostalgia has taken over pop culture at the expense of new ideas.', category: 'Culture' },
  { text: 'Book clubs are more valuable for socializing than for actually discussing books.', category: 'Culture' },
  { text: 'Fan culture has become more toxic than supportive.', category: 'Culture' },
  { text: 'True crime content glorifies violence more than it educates.', category: 'Culture' },
  { text: 'Celebrity worship says more about us than about celebrities.', category: 'Culture' },
  { text: 'Karaoke is one of the most underrated social activities.', category: 'Culture' },
  { text: 'Museums need to modernize or risk becoming irrelevant.', category: 'Culture' },
  { text: 'Fashion trends cycle faster now because of social media, not because of creativity.', category: 'Culture' },
  { text: 'Stand-up comedy is harder to get right today than it was a decade ago.', category: 'Culture' },
  { text: 'Traveling just to say you\'ve been somewhere is different from actually experiencing a place.', category: 'Culture' },
  { text: 'Physical media like vinyl and DVDs will make a lasting comeback, not just a nostalgic blip.', category: 'Culture' },
  { text: 'Wedding costs have spiraled out of control for no good reason.', category: 'Culture' },
  { text: 'Ghosting has become an acceptable way to end relationships.', category: 'Culture' },
  { text: 'Book-to-film / series adaptations rarely capture what made the book great.', category: 'Culture' },
  { text: 'Video essays have become more insightful than traditional criticism.', category: 'Culture' },
  { text: 'Small talk is an underrated social skill, not a waste of time.', category: 'Culture' },
  { text: 'Holiday and festival traditions matter less to younger generations than they used to.', category: 'Culture' },
  { text: 'Theme parks and big entertainment venues are overpriced for what they offer today.', category: 'Culture' },
  { text: 'Autobiographies are more honest than authorized biographies.', category: 'Culture' },
  { text: 'Street art belongs in the same category as gallery art.', category: 'Culture' },
  { text: 'Binge-watching has ruined the way we experience shows.', category: 'Culture' },
  { text: 'Handwritten letters are more meaningful than any text message.', category: 'Culture' },

  // Sports
  { text: 'Pro athletes are paid too much for what they do.', category: 'Sports' },
  { text: 'College / university athletes should be paid fairly for their contribution.', category: 'Sports' },
  { text: 'Cricket is more skillful and strategic than many people give it credit for.', category: 'Sports' },
  { text: 'Tackling and heavy contact should be restricted in youth sports.', category: 'Sports' },
  { text: 'Instant replay has ruined the flow of live sports.', category: 'Sports' },
  { text: 'Boxing and similar combat sports should face stricter safety rules.', category: 'Sports' },
  { text: 'Many major leagues are more entertainment than pure sport at this point.', category: 'Sports' },
  { text: 'Female athletes should earn the same prize money as male athletes in comparable events.', category: 'Sports' },
  { text: 'Olympic athletes deserve far higher compensation and support than they get.', category: 'Sports' },
  { text: 'Fighting / violence in contact sports should be more tightly regulated.', category: 'Sports' },
  { text: 'Performance-enhancing drugs should be allowed in pro sports under controlled conditions.', category: 'Sports' },
  { text: 'Trash-talking is a legitimate part of competition.', category: 'Sports' },
  { text: 'Some traditional rules in older sports have outlived their usefulness.', category: 'Sports' },
  { text: 'Newer sports and formats will keep challenging older ones in popularity.', category: 'Sports' },
  { text: 'Cheerleading and similar activities should be classified as sports where appropriate.', category: 'Sports' },
  { text: 'Ultra-endurance events can be bad for long-term health if done excessively.', category: 'Sports' },
  { text: 'Sports betting has corrupted modern sports leagues.', category: 'Sports' },
  { text: 'Youth sports have become too competitive too early.', category: 'Sports' },
  { text: 'Participation trophies do more harm than good.', category: 'Sports' },
  { text: 'The Olympics should consider cost and accessibility when adding or keeping sports.', category: 'Sports' },
  { text: 'Home-field / home-crowd advantage matters more than most fans realize.', category: 'Sports' },
  { text: 'Esports deserve to be treated as seriously as traditional sports.', category: 'Sports' },
  { text: 'A salary cap or similar balance mechanism should exist in every major professional league.', category: 'Sports' },
  { text: 'Some sports take too long to hold mainstream appeal for new audiences.', category: 'Sports' },
  { text: 'Overtime and sudden-death rules often favor one side too much.', category: 'Sports' },
  { text: 'Young athletes should be allowed to profit from their name and likeness earlier.', category: 'Sports' },
  { text: 'Sports commentary has gotten worse as analytics have taken over.', category: 'Sports' },
  { text: 'High-contact sports should have stricter age limits for children.', category: 'Sports' },
  { text: 'Super teams built through free agency or auctions are bad for competitive balance.', category: 'Sports' },
  { text: 'Rivalry matches matter more to fans than championships in many cases.', category: 'Sports' },
  { text: 'Contract holdouts are justified when a player is clearly underpaid relative to the market.', category: 'Sports' },
  { text: 'Rule changes that favor scoring can change a sport for better or worse.', category: 'Sports' },
  { text: 'Extreme sports deserve more mainstream coverage.', category: 'Sports' },
  { text: 'Retired jersey numbers should be reserved for truly legendary players only.', category: 'Sports' },
  { text: 'Sports dynasties are bad for a league\'s long-term popularity.', category: 'Sports' },
  { text: 'Home teams get too much benefit of the doubt from referees / umpires.', category: 'Sports' },
  { text: 'Off-season training matters more to a player\'s career than raw talent.', category: 'Sports' },
  { text: 'Fantasy sports have changed how fans watch games — not always for the better.', category: 'Sports' },
  { text: 'Team traditions matter more to fan loyalty than a team\'s win record.', category: 'Sports' },

  // Philosophy
  { text: 'Life has no inherent meaning. We create our own purpose.', category: 'Philosophy' },
  { text: 'Free will is an illusion.', category: 'Philosophy' },
  { text: 'It\'s better to know a hard truth than a comforting lie.', category: 'Philosophy' },
  { text: 'Suffering is necessary for personal growth.', category: 'Philosophy' },
  { text: 'Happiness is a choice, not a circumstance.', category: 'Philosophy' },
  { text: 'Death is what gives life its meaning.', category: 'Philosophy' },
  { text: 'Morality is invented by humans, not discovered.', category: 'Philosophy' },
  { text: 'Time is a human construct, not a real feature of the universe.', category: 'Philosophy' },
  { text: 'A simulated existence indistinguishable from reality is just as valuable.', category: 'Philosophy' },
  { text: 'It\'s better to be a satisfied fool than a dissatisfied philosopher.', category: 'Philosophy' },
  { text: 'The ends sometimes do justify the means.', category: 'Philosophy' },
  { text: 'Solitude is more honest than community.', category: 'Philosophy' },
  { text: 'Personal identity does not survive transformation over time.', category: 'Philosophy' },
  { text: 'Forgiveness is a gift to yourself, not the other person.', category: 'Philosophy' },
  { text: 'Boredom is the root of every truly creative act.', category: 'Philosophy' },
  { text: 'Beauty is objective, not only in the eye of the beholder.', category: 'Philosophy' },
  { text: 'Fully knowing yourself is impossible.', category: 'Philosophy' },
  { text: 'Tradition is wisdom that has survived testing.', category: 'Philosophy' },
  { text: 'A life examined too closely is not worth living.', category: 'Philosophy' },
  { text: 'Kindness is a stronger foundation for a good life than intelligence.', category: 'Philosophy' },
  { text: 'Regret is more useful than people give it credit for.', category: 'Philosophy' },
  { text: 'True altruism does not exist; every good deed serves the self in some way.', category: 'Philosophy' },
  { text: 'Envy can be a productive emotion if you let it be.', category: 'Philosophy' },
  { text: 'Wisdom comes from experience, not only from books.', category: 'Philosophy' },
  { text: 'A person\'s character is best judged by how they treat strangers, not friends.', category: 'Philosophy' },
  { text: 'Curiosity matters more than discipline for a fulfilling life.', category: 'Philosophy' },
  { text: 'Silence reveals more about a person than speech does.', category: 'Philosophy' },
  { text: 'The unexamined choice is worse than the wrong choice.', category: 'Philosophy' },
  { text: 'Gratitude is a skill, not just a feeling.', category: 'Philosophy' },
  { text: 'Justice matters more than mercy.', category: 'Philosophy' },
  { text: 'A person cannot be truly free while depending on others.', category: 'Philosophy' },
  { text: 'Ambition and contentment cannot easily coexist.', category: 'Philosophy' },
  { text: 'Memory defines who we are more than our present actions do.', category: 'Philosophy' },
  { text: 'Doubt is more valuable than certainty.', category: 'Philosophy' },
  { text: 'Loyalty should have limits.', category: 'Philosophy' },
  { text: 'Humility is the hardest virtue to practice.', category: 'Philosophy' },
  { text: 'The relationships you keep say more about you than the achievements you chase.', category: 'Philosophy' },
  { text: 'Pain teaches more effectively than pleasure does.', category: 'Philosophy' },
  { text: 'Choosing not to choose is still a choice with consequences.', category: 'Philosophy' },
  { text: 'Authenticity matters more than likability.', category: 'Philosophy' },
  { text: 'A good question is more valuable than a good answer.', category: 'Philosophy' },

  // Politics
  { text: 'Voting should be mandatory for every eligible citizen.', category: 'Politics' },
  { text: 'Term limits should apply to every elected office.', category: 'Politics' },
  { text: 'The two-party / multi-party system as it currently works is broken beyond easy repair.', category: 'Politics' },
  { text: 'Social media has done more harm than good for democracy.', category: 'Politics' },
  { text: 'Politicians should be banned from owning individual stocks while in office.', category: 'Politics' },
  { text: 'The voting age should be raised or kept carefully considered.', category: 'Politics' },
  { text: 'Ranked-choice or preferential voting should be adopted more widely.', category: 'Politics' },
  { text: 'Higher courts should have clearer term limits or fixed tenures.', category: 'Politics' },
  { text: 'Every citizen should serve some form of public or national service.', category: 'Politics' },
  { text: 'Lobbying should be far more tightly regulated or restricted.', category: 'Politics' },
  { text: 'Political ads on social media should face much stricter rules.', category: 'Politics' },
  { text: 'The minimum wage should be tied more closely to inflation or cost of living.', category: 'Politics' },
  { text: 'Borders remain a necessary concept even in a connected world.', category: 'Politics' },
  { text: 'Prisons should focus more on rehabilitation than pure punishment.', category: 'Politics' },
  { text: 'The death penalty should be abolished or used only in the rarest cases.', category: 'Politics' },
  { text: 'Foreign aid and domestic priorities need better balance.', category: 'Politics' },
  { text: 'All elections should have stronger public funding and spending limits.', category: 'Politics' },
  { text: 'Direct democracy works better than pure representative democracy at smaller scales.', category: 'Politics' },
  { text: 'Political parties should face more internal democracy and transparency.', category: 'Politics' },
  { text: 'Local elections deserve as much media attention as national ones.', category: 'Politics' },
  { text: 'Election day should be a public holiday or more accessible.', category: 'Politics' },
  { text: 'Political campaigns should have strict spending limits.', category: 'Politics' },
  { text: 'Judges should be appointed through more transparent and less partisan processes.', category: 'Politics' },
  { text: 'Gerrymandering / delimitation should be handled by independent commissions.', category: 'Politics' },
  { text: 'Citizens should be able to recall elected officials more easily.', category: 'Politics' },
  { text: 'Public trust in government is lower today mostly because of transparency failures, not only policy failures.', category: 'Politics' },
  { text: 'Civic education should be mandatory before high school graduation.', category: 'Politics' },
  { text: 'Political debates should be moderated more fairly and with less bias.', category: 'Politics' },
  { text: 'Whistleblowers deserve stronger legal protection than they currently get.', category: 'Politics' },
  { text: 'Government budgets should be easier for the average citizen to understand.', category: 'Politics' },
  { text: 'Local government has more influence on daily life than most people realize.', category: 'Politics' },
  { text: 'Term limits or clearer accountability for unelected advisors would improve governance.', category: 'Politics' },
  { text: 'Online voting would increase turnout but the security risks are still significant.', category: 'Politics' },
  { text: 'Public officials should be required to hold regular town halls or public interactions.', category: 'Politics' },
  { text: 'Referendums and public consultations should be used more often for major issues.', category: 'Politics' },
  { text: 'Campaign donations should be capped regardless of the source.', category: 'Politics' },
  { text: 'Government transparency laws should apply equally across branches and levels.', category: 'Politics' },
  { text: 'Redistricting / delimitation should happen on a clearer and more regular schedule.', category: 'Politics' },
  { text: 'Public servants should face stronger penalties for corruption than ordinary citizens.', category: 'Politics' },

  // Health
  { text: 'Losing weight using medication is not the same as losing weight through diet and exercise.', category: 'Health' },
  { text: 'Therapy and mental health support should be far more accessible and affordable.', category: 'Health' },
  { text: 'Mental health days should be treated the same as sick days.', category: 'Health' },
  { text: 'A plant-forward diet is generally healthier than a heavy meat-based one for most people.', category: 'Health' },
  { text: 'Fitness influencers do more harm than good.', category: 'Health' },
  { text: 'The eight-hour sleep rule is overrated; quality matters more than exact hours.', category: 'Health' },
  { text: 'Recreational cannabis should be legal and regulated everywhere.', category: 'Health' },
  { text: 'Health insurance should not be tied only to employment.', category: 'Health' },
  { text: 'Cosmetic procedures on minors should face much stricter rules.', category: 'Health' },
  { text: 'Energy drinks and high-caffeine products should be restricted for under-eighteens.', category: 'Health' },
  { text: 'Modern medicine sometimes over-prescribes antidepressants and similar drugs.', category: 'Health' },
  { text: 'Drinking alcohol is worse for you than moderate cannabis use in many respects.', category: 'Health' },
  { text: 'Walking ten thousand steps a day is more marketing than strict science.', category: 'Health' },
  { text: 'All packaged foods should be required to display a clear health rating.', category: 'Health' },
  { text: 'Universal healthcare access is a basic human right.', category: 'Health' },
  { text: 'Multivitamins are mostly a waste of money for healthy adults.', category: 'Health' },
  { text: 'Sleep tracking apps create more anxiety than they solve for many people.', category: 'Health' },
  { text: 'Fasting diets are more hype than solid science for most people.', category: 'Health' },
  { text: 'Cold plunges and similar trends are more placebo than proven physical benefit for many.', category: 'Health' },
  { text: 'Doctors should be required to explain treatment costs before prescribing them.', category: 'Health' },
  { text: 'Preventive care should be fully covered by every insurance or public health plan.', category: 'Health' },
  { text: 'Burnout should be treated as a medical and social condition, not just a personal failing.', category: 'Health' },
  { text: 'Sugar and ultra-processed foods should face stronger regulation like tobacco once did.', category: 'Health' },
  { text: 'Wearing sunscreen daily matters more than most people realize.', category: 'Health' },
  { text: 'Gyms often overcomplicate what it actually takes to get fit.', category: 'Health' },
  { text: 'Mental health screenings should be part of every annual health check.', category: 'Health' },
  { text: 'Fad diets do more harm than the weight they claim to help you lose.', category: 'Health' },
  { text: 'Hospitals and clinics should be required to post prices for common procedures publicly.', category: 'Health' },
  { text: 'Skipping breakfast is not as harmful as it\'s often made out to be.', category: 'Health' },
  { text: 'Telehealth appointments are just as effective as in-person visits for many concerns.', category: 'Health' },
  { text: 'Protein supplements are overused by people who don\'t actually need them.', category: 'Health' },
  { text: 'Chronic stress does more long-term damage than a poor diet in many cases.', category: 'Health' },
  { text: 'Standing desks are more marketing than meaningful health benefit for most people.', category: 'Health' },
  { text: 'Health class in school should include mental health, not just physical health.', category: 'Health' },
  { text: 'Painkiller dependency starts more often with legal prescriptions than illegal drugs.', category: 'Health' },
  { text: 'Annual physicals catch fewer problems than people assume.', category: 'Health' },
  { text: 'A four-day work week would improve public health more than many wellness programs.', category: 'Health' },
  { text: 'Elective surgery should require a mandatory waiting or cooling-off period.', category: 'Health' },

  // Environment
  { text: 'Air travel should be limited or taxed more heavily for frequent flyers.', category: 'Environment' },
  { text: 'Nuclear energy is one of the most realistic paths to lower emissions.', category: 'Environment' },
  { text: 'Single-use plastic packaging should be banned or heavily restricted by 2030.', category: 'Environment' },
  { text: 'Climate change is the most important issue of the next 20 years.', category: 'Environment' },
  { text: 'Cars should be restricted or discouraged in dense city centres.', category: 'Environment' },
  { text: 'Recycling, as currently practiced in many places, is less effective than people think.', category: 'Environment' },
  { text: 'Water-intensive lawns and landscaping should be restricted in drought-prone areas.', category: 'Environment' },
  { text: 'Fast fashion should face much stronger regulation.', category: 'Environment' },
  { text: 'Bottled water should be discouraged or restricted wherever safe tap water is available.', category: 'Environment' },
  { text: 'Cruise ships and high-impact tourism should face stricter environmental rules.', category: 'Environment' },
  { text: 'Owning multiple cars per household should be taxed or discouraged more strongly.', category: 'Environment' },
  { text: 'National parks and sensitive natural areas should limit private vehicle access.', category: 'Environment' },
  { text: 'Companies that pollute should be charged for the full environmental damage they cause.', category: 'Environment' },
  { text: 'Going paperless often saves more resources than recycling alone.', category: 'Environment' },
  { text: 'Meat consumption should reflect more of its environmental cost through pricing or policy.', category: 'Environment' },
  { text: 'Every new building should be required to include some form of renewable energy or efficiency measures.', category: 'Environment' },
  { text: 'Composting and organic waste separation should be mandatory in cities with collection systems.', category: 'Environment' },
  { text: 'Fast delivery culture is worse for the environment than people admit.', category: 'Environment' },
  { text: 'Golf courses and similar water-heavy amenities use more resources than they\'re often worth in dry regions.', category: 'Environment' },
  { text: 'Carbon offsets are more marketing than measurable impact in many cases.', category: 'Environment' },
  { text: 'Public transit should be affordable or free to reduce car dependency.', category: 'Environment' },
  { text: 'Zoos and aquariums can do more for conservation than critics sometimes give them credit for.', category: 'Environment' },
  { text: 'Electric vehicles are not as clean as marketed once full production and battery impact are factored in.', category: 'Environment' },
  { text: 'Every new home should be encouraged or required to include rainwater harvesting where feasible.', category: 'Environment' },
  { text: 'Reforestation and protection of existing forests matter as much as reducing emissions.', category: 'Environment' },
  { text: 'Packaging waste is a bigger problem than plastic straws ever were.', category: 'Environment' },
  { text: 'Space tourism is hard to justify given its environmental and resource cost.', category: 'Environment' },
  { text: 'Urban green spaces should be prioritized over parking lots in every new development.', category: 'Environment' },
];