// src/features/recordings/topics.data.js
//
// Static topics, tagged by category — spinning happens entirely
// client-side. Backend just receives whichever `text` string is picked
// as `topic` on recording creation, nothing category-related is sent.

export const CATEGORIES = [
  'Technology',
  'Business',
  'Education',
  'Culture',
  'Sports',
  'Philosophy',
  'Politics',
  'Health',
  'Environment',
];

export const TOPICS = [
  // Technology (45)
  { text: 'AI will replace most software engineers within ten years.', category: 'Technology' },
  { text: 'Smartphones have made us less social, not more.', category: 'Technology' },
  { text: "Self-driving cars should be the norm once they're proven safer than humans.", category: 'Technology' },
  { text: 'Tech companies should be banned from selling personal data.', category: 'Technology' },
  { text: 'Cryptocurrency will eventually replace traditional money.', category: 'Technology' },
  { text: 'Children under thirteen should not be allowed on social media.', category: 'Technology' },
  { text: 'Algorithms shape your opinions more than your friends do.', category: 'Technology' },
  { text: 'Open source software has done more for humanity than any tech company.', category: 'Technology' },
  { text: 'Smart speakers in the home are a privacy disaster waiting to happen.', category: 'Technology' },
  { text: 'VR will eventually replace most travel.', category: 'Technology' },
  { text: 'Coding should be a required class in high school.', category: 'Technology' },
  { text: 'All bot accounts should be banned from social media.', category: 'Technology' },
  { text: 'The internet was better before algorithms took over social media.', category: 'Technology' },
  { text: 'Apps should be required to ship with a delete-my-data button.', category: 'Technology' },
  { text: 'Facial recognition in public spaces should be banned.', category: 'Technology' },
  { text: 'Recording people using Meta Ray Bans in public spaces should be banned.', category: 'Technology' },
  { text: 'Big tech companies are more powerful than most governments.', category: 'Technology' },
  { text: 'The smartphone has done more harm to teenagers than alcohol.', category: 'Technology' },
  { text: 'Wearable health trackers do more harm than good.', category: 'Technology' },
  { text: 'Passwords will be obsolete within the next decade.', category: 'Technology' },
  { text: 'Everyone should use a password manager.', category: 'Technology' },
  { text: 'Video calls have made people worse at reading body language.', category: 'Technology' },
  { text: 'E-books are better than physical books for retention.', category: 'Technology' },
  { text: 'AI-generated art should be clearly labeled as AI-made.', category: 'Technology' },
  { text: 'Right-to-repair laws should require manufacturers to sell spare parts to consumers.', category: 'Technology' },
  { text: 'Autonomous delivery drones will be commonplace within ten years.', category: 'Technology' },
  { text: 'Online anonymity does more good than harm.', category: 'Technology' },
  { text: 'Robots will eventually make better caregivers for the elderly than humans.', category: 'Technology' },
  { text: 'Every website should be required to offer a version that doesn\'t track visitors.', category: 'Technology' },
  { text: 'The next major computing platform will be wearable, not mobile.', category: 'Technology' },
  { text: 'Chatbots should be required to disclose that they are not human.', category: 'Technology' },
  { text: '3D printing will disrupt manufacturing more than the internet disrupted media.', category: 'Technology' },
  { text: 'Biometric login is safer than passwords.', category: 'Technology' },
  { text: 'AI coding assistants will make traditional computer science degrees less valuable.', category: 'Technology' },
  { text: 'Space exploration should be led by private companies, not governments.', category: 'Technology' },
  { text: 'The metaverse will never replace real-world socializing.', category: 'Technology' },
  { text: 'Encrypted messaging apps should never include a government backdoor.', category: 'Technology' },
  { text: 'Most people would be happier using a basic phone instead of a smartphone.', category: 'Technology' },
  { text: 'AI companions will become a normal part of romantic life within a generation.', category: 'Technology' },
  { text: 'Companies should be required to compensate users automatically after a data breach.', category: 'Technology' },
  { text: 'Digital minimalism is a trend that won\'t last.', category: 'Technology' },
  { text: 'Legal screen-time limits on kids\' devices would work better than relying on parents alone.', category: 'Technology' },
  { text: 'Cloud storage has made people careless about backing up their own data.', category: 'Technology' },
  { text: 'Deepfakes will make video evidence unreliable in court within ten years.', category: 'Technology' },
  { text: 'Every smart home device should have a physical off switch for its microphone.', category: 'Technology' },

  // Business (42)
  { text: 'Remote work is more productive than working in an office.', category: 'Business' },
  { text: 'Companies should be required to publish every employee\'s salary.', category: 'Business' },
  { text: 'The four-day work week should be the new standard.', category: 'Business' },
  { text: 'There are no ethical billionaires.', category: 'Business' },
  { text: 'Unpaid internships should not exist.', category: 'Business' },
  { text: 'Every big decision by a public company should be put up to a vote by shareholders.', category: 'Business' },
  { text: 'The gig economy is a step backward for labor rights.', category: 'Business' },
  { text: 'Branding has become more important than the product itself.', category: 'Business' },
  { text: 'Customer service has gotten worse in every industry over the past decade.', category: 'Business' },
  { text: 'Inheritances above ten million dollars should be given to the government.', category: 'Business' },
  { text: 'Everyone should retire at 65.', category: 'Business' },
  { text: 'Tipping culture has spiraled out of control.', category: 'Business' },
  { text: 'Performance reviews are a waste of time.', category: 'Business' },
  { text: 'Office dress codes are pointless in the modern era.', category: 'Business' },
  { text: 'Patents stifle innovation more than they protect it.', category: 'Business' },
  { text: 'Every job posting should be required to list its salary range.', category: 'Business' },
  { text: 'Layoffs delivered by video call should be illegal.', category: 'Business' },
  { text: 'Non-compete agreements should be banned nationwide.', category: 'Business' },
  { text: 'Startups fail more often from bad co-founders than bad ideas.', category: 'Business' },
  { text: 'Open-plan offices hurt productivity more than they help collaboration.', category: 'Business' },
  { text: 'Employees should be able to unionize without employer interference.', category: 'Business' },
  { text: 'A college degree should not be required for most entry-level jobs.', category: 'Business' },
  { text: 'Every company should offer unlimited vacation policies.', category: 'Business' },
  { text: 'The traditional 9-to-5 workday no longer makes sense.', category: 'Business' },
  { text: 'Severance pay should be required by law after layoffs.', category: 'Business' },
  { text: 'Business ethics classes make little difference in how executives actually behave.', category: 'Business' },
  { text: 'Franchising is a better path to wealth than starting an original business.', category: 'Business' },
  { text: 'Middle management is mostly unnecessary overhead.', category: 'Business' },
  { text: 'Shareholders care too much about quarterly profits and too little about long-term growth.', category: 'Business' },
  { text: 'Small businesses deserve more tax breaks than large corporations.', category: 'Business' },
  { text: 'Job-hopping is the fastest way to grow your salary.', category: 'Business' },
  { text: 'Company loyalty is a myth that only benefits employers.', category: 'Business' },
  { text: 'Mentorship matters more than raw talent for career success.', category: 'Business' },
  { text: 'Return-to-office mandates are more about control than productivity.', category: 'Business' },
  { text: 'AI will create more jobs than it destroys.', category: 'Business' },
  { text: 'Meetings that could be an email are a bigger problem than most companies admit.', category: 'Business' },
  { text: 'Salary negotiation should be taught in every college.', category: 'Business' },
  { text: 'Employee stock options are overrated as compensation.', category: 'Business' },
  { text: 'Family businesses are harder to scale than founder-led startups.', category: 'Business' },
  { text: 'Networking matters more than credentials when it comes to getting hired.', category: 'Business' },
  { text: 'Businesses should be required to publicly disclose their environmental impact.', category: 'Business' },
  { text: 'Great leaders are made, not born.', category: 'Business' },

  // Education (40)
  { text: 'AI tutors will be better than human teachers within five years.', category: 'Education' },
  { text: 'College is the best path to success.', category: 'Education' },
  { text: 'Standardized testing is not a great way to assess a student\'s capabilities.', category: 'Education' },
  { text: 'Schools should be required to teach financial literacy.', category: 'Education' },
  { text: 'Students should be allowed to use AI while doing homework.', category: 'Education' },
  { text: 'Every student should learn how to cook before they graduate high school.', category: 'Education' },
  { text: 'Public schools should be funded equally regardless of zip code.', category: 'Education' },
  { text: 'Every student should learn a second language fluently before graduating.', category: 'Education' },
  { text: 'Recess should be mandatory at every grade level.', category: 'Education' },
  { text: 'Teachers should be paid much more.', category: 'Education' },
  { text: 'Online learning has made students worse, not better.', category: 'Education' },
  { text: 'Required reading lists should include far more women and people of color.', category: 'Education' },
  { text: 'Mandatory school uniforms make students more equal, not less.', category: 'Education' },
  { text: 'Final exams measure memorization, not understanding.', category: 'Education' },
  { text: 'Grades do more harm than good to student motivation.', category: 'Education' },
  { text: 'Every school should offer mental health classes.', category: 'Education' },
  { text: 'Trade school should be marketed as equally valuable as a four-year degree.', category: 'Education' },
  { text: 'Class sizes should be capped at 20 students.', category: 'Education' },
  { text: 'Homework should be optional in elementary school.', category: 'Education' },
  { text: 'Every student should take a public speaking class before graduating.', category: 'Education' },
  { text: 'School should start later in the day for teenagers.', category: 'Education' },
  { text: 'Cursive handwriting should still be taught in schools.', category: 'Education' },
  { text: 'Group projects do more to hurt learning than help it.', category: 'Education' },
  { text: 'Attendance policies are more about compliance than actual learning.', category: 'Education' },
  { text: 'Gifted programs do more harm than good by separating students too early.', category: 'Education' },
  { text: 'Letter grades should be replaced with detailed written feedback.', category: 'Education' },
  { text: 'Every student should learn to touch-type before middle school.', category: 'Education' },
  { text: 'School sports should not require a minimum GPA to participate.', category: 'Education' },
  { text: 'Teachers should be allowed to fail students for excessive absences alone.', category: 'Education' },
  { text: 'Field trips are one of the most underrated parts of education.', category: 'Education' },
  { text: 'Every school should teach media literacy as its own subject.', category: 'Education' },
  { text: 'Elite universities admit too many students based on legacy status.', category: 'Education' },
  { text: 'Year-round schooling would benefit students more than long summer breaks.', category: 'Education' },
  { text: 'Students should be graded on effort as much as results.', category: 'Education' },
  { text: 'Parents should have less influence over school curriculum decisions.', category: 'Education' },
  { text: 'Learning a musical instrument should be mandatory in elementary school.', category: 'Education' },
  { text: 'Vocational skills should be taught alongside academics starting in middle school.', category: 'Education' },
  { text: 'Class rank does more to discourage students than motivate them.', category: 'Education' },
  { text: 'Every student should complete a community service project before graduating.', category: 'Education' },
  { text: 'Study abroad programs should be affordable for every student, not just the wealthy.', category: 'Education' },

  // Culture (42)
  { text: 'Cancel culture has gone too far.', category: 'Culture' },
  { text: 'Tipping should be abolished and replaced with higher wages.', category: 'Culture' },
  { text: 'Reality TV has done more harm than good for society.', category: 'Culture' },
  { text: 'Streaming services killed the magic of going to the movies.', category: 'Culture' },
  { text: 'Dating apps have made romance worse.', category: 'Culture' },
  { text: 'Pop music today is worse than it was twenty years ago.', category: 'Culture' },
  { text: 'Sequels and remakes prove Hollywood is out of ideas.', category: 'Culture' },
  { text: 'Influencer marketing has destroyed authentic recommendation.', category: 'Culture' },
  { text: 'Tattoos have lost their edge now that everyone has them.', category: 'Culture' },
  { text: 'Public libraries are the most underrated institution in society.', category: 'Culture' },
  { text: 'Modern architecture is uglier than what it replaced.', category: 'Culture' },
  { text: 'Award shows are no longer culturally relevant.', category: 'Culture' },
  { text: 'Memes have replaced traditional satire as cultural commentary.', category: 'Culture' },
  { text: 'Reading fiction is just as valuable as reading non-fiction.', category: 'Culture' },
  { text: 'Live concerts are not worth the price anymore.', category: 'Culture' },
  { text: 'Podcasts have replaced books for most adults.', category: 'Culture' },
  { text: 'Modern art is mostly a scam.', category: 'Culture' },
  { text: 'TikTok is rotting attention spans across all generations.', category: 'Culture' },
  { text: 'Every adult should travel solo at least once.', category: 'Culture' },
  { text: 'Marriage as an institution is on its way out.', category: 'Culture' },
  { text: 'Nostalgia has taken over pop culture at the expense of new ideas.', category: 'Culture' },
  { text: 'Book clubs are more valuable for socializing than for actually discussing books.', category: 'Culture' },
  { text: 'Fan culture has become more toxic than supportive.', category: 'Culture' },
  { text: 'True crime content glorifies violence more than it educates.', category: 'Culture' },
  { text: 'Celebrity worship says more about us than about celebrities.', category: 'Culture' },
  { text: 'Karaoke is one of the most underrated social activities.', category: 'Culture' },
  { text: 'Museums need to modernize or risk becoming irrelevant.', category: 'Culture' },
  { text: 'Fashion trends cycle faster now because of social media, not because of creativity.', category: 'Culture' },
  { text: 'Stand-up comedy is harder to get right today than it was a decade ago.', category: 'Culture' },
  { text: 'Traveling to say you\'ve been somewhere is different from actually experiencing a place.', category: 'Culture' },
  { text: 'Physical media like vinyl and DVDs will make a lasting comeback, not just a nostalgic blip.', category: 'Culture' },
  { text: 'Wedding costs have spiraled out of control for no good reason.', category: 'Culture' },
  { text: 'Ghosting has become an acceptable way to end relationships.', category: 'Culture' },
  { text: 'Book-to-film adaptations rarely capture what made the book great.', category: 'Culture' },
  { text: 'Video essays have become more insightful than traditional film criticism.', category: 'Culture' },
  { text: 'Small talk is an underrated social skill, not a waste of time.', category: 'Culture' },
  { text: 'Holiday traditions matter less to younger generations than they used to.', category: 'Culture' },
  { text: 'Theme parks are overpriced for what they offer today.', category: 'Culture' },
  { text: 'Autobiographies are more honest than authorized biographies.', category: 'Culture' },
  { text: 'Street art belongs in the same category as gallery art.', category: 'Culture' },
  { text: 'Binge-watching has ruined the way we experience TV shows.', category: 'Culture' },
  { text: 'Handwritten letters are more meaningful than any text message.', category: 'Culture' },

  // Sports (39)
  { text: 'Pro athletes are paid too much for what they do.', category: 'Sports' },
  { text: 'College athletes should be paid like professionals.', category: 'Sports' },
  { text: 'Soccer is more skillful than American football.', category: 'Sports' },
  { text: 'Tackling should be banned in youth football.', category: 'Sports' },
  { text: 'Instant replay has ruined the flow of live sports.', category: 'Sports' },
  { text: 'Boxing should be banned for being too dangerous.', category: 'Sports' },
  { text: 'The NFL is more entertainment than sport at this point.', category: 'Sports' },
  { text: 'Female athletes should earn the same prize money as male athletes.', category: 'Sports' },
  { text: 'Olympic athletes deserve far higher compensation than they get.', category: 'Sports' },
  { text: 'Fighting in hockey should be banned.', category: 'Sports' },
  { text: 'Performance-enhancing drugs should be allowed in pro sports.', category: 'Sports' },
  { text: 'Trash-talking is a legitimate part of competition.', category: 'Sports' },
  { text: 'The designated hitter rule ruined baseball.', category: 'Sports' },
  { text: 'Pickleball will replace tennis in popularity within a decade.', category: 'Sports' },
  { text: 'Cheerleading should be classified as a sport.', category: 'Sports' },
  { text: 'Marathons are bad for your long-term health.', category: 'Sports' },
  { text: 'Sports betting has corrupted modern sports leagues.', category: 'Sports' },
  { text: 'Youth sports have become too competitive too early.', category: 'Sports' },
  { text: 'Participation trophies do more harm than good.', category: 'Sports' },
  { text: 'The Olympics should drop sports that require expensive equipment to keep costs fair.', category: 'Sports' },
  { text: 'Home-field advantage matters more than most fans realize.', category: 'Sports' },
  { text: 'Esports deserve to be treated as seriously as traditional sports.', category: 'Sports' },
  { text: 'A salary cap should exist in every major professional league.', category: 'Sports' },
  { text: 'Golf takes too long to hold mainstream appeal.', category: 'Sports' },
  { text: 'Overtime rules in football favor the team that wins the coin toss too much.', category: 'Sports' },
  { text: 'High school athletes should be allowed to profit from their name and likeness.', category: 'Sports' },
  { text: 'Sports commentary has gotten worse as analytics have taken over.', category: 'Sports' },
  { text: 'Youth football should not exist before high school.', category: 'Sports' },
  { text: 'Super teams built through free agency are bad for competitive balance.', category: 'Sports' },
  { text: 'Rivalry games matter more to fans than championships.', category: 'Sports' },
  { text: 'Contract holdouts are justified when a player is underpaid relative to the market.', category: 'Sports' },
  { text: 'The three-point line changed basketball for the worse.', category: 'Sports' },
  { text: 'Extreme sports deserve more mainstream coverage.', category: 'Sports' },
  { text: 'Retired jersey numbers should be reserved for truly legendary players only.', category: 'Sports' },
  { text: 'Sports dynasties are bad for a league\'s long-term popularity.', category: 'Sports' },
  { text: 'Home teams get too much benefit of the doubt from referees.', category: 'Sports' },
  { text: 'Off-season training matters more to a player\'s career than raw talent.', category: 'Sports' },
  { text: 'Fantasy sports have changed how fans watch games for the worse.', category: 'Sports' },
  { text: 'Team traditions matter more to fan loyalty than a team\'s win record.', category: 'Sports' },

  // Philosophy (41)
  { text: 'Life has no inherent meaning. We create our own purpose.', category: 'Philosophy' },
  { text: 'Free will is an illusion.', category: 'Philosophy' },
  { text: 'It\'s better to know a hard truth than a comforting lie.', category: 'Philosophy' },
  { text: 'Suffering is necessary for personal growth.', category: 'Philosophy' },
  { text: 'Happiness is a choice, not a circumstance.', category: 'Philosophy' },
  { text: 'Death is what gives life its meaning.', category: 'Philosophy' },
  { text: 'Morality is invented by humans, not discovered.', category: 'Philosophy' },
  { text: 'Time is a human construct, not a real feature of the universe.', category: 'Philosophy' },
  { text: 'A simulated existence indistinguishable from reality is just as valuable.', category: 'Philosophy' },
  { text: 'It\'s better to be a satisfied fool than a dissatisfied philosopher.', category: 'Philosophy' },
  { text: 'The ends sometimes do justify the means.', category: 'Philosophy' },
  { text: 'Solitude is more honest than community.', category: 'Philosophy' },
  { text: 'Personal identity does not survive transformation over time.', category: 'Philosophy' },
  { text: 'Forgiveness is a gift to yourself, not the other person.', category: 'Philosophy' },
  { text: 'Boredom is the root of every truly creative act.', category: 'Philosophy' },
  { text: 'Beauty is objective, not in the eye of the beholder.', category: 'Philosophy' },
  { text: 'Fully knowing yourself is impossible.', category: 'Philosophy' },
  { text: 'Tradition is wisdom that has survived testing.', category: 'Philosophy' },
  { text: 'A life examined too closely is not worth living.', category: 'Philosophy' },
  { text: 'Kindness is a stronger foundation for a good life than intelligence.', category: 'Philosophy' },
  { text: 'Regret is more useful than people give it credit for.', category: 'Philosophy' },
  { text: 'True altruism does not exist; every good deed serves the self in some way.', category: 'Philosophy' },
  { text: 'Envy can be a productive emotion if you let it be.', category: 'Philosophy' },
  { text: 'Wisdom comes from experience, not from books.', category: 'Philosophy' },
  { text: 'A person\'s character is best judged by how they treat strangers, not friends.', category: 'Philosophy' },
  { text: 'Curiosity matters more than discipline for a fulfilling life.', category: 'Philosophy' },
  { text: 'Silence reveals more about a person than speech does.', category: 'Philosophy' },
  { text: 'The unexamined choice is worse than the wrong choice.', category: 'Philosophy' },
  { text: 'Gratitude is a skill, not a feeling.', category: 'Philosophy' },
  { text: 'Justice matters more than mercy.', category: 'Philosophy' },
  { text: 'A person cannot be truly free while depending on others.', category: 'Philosophy' },
  { text: 'Ambition and contentment cannot coexist.', category: 'Philosophy' },
  { text: 'Memory defines who we are more than our present actions do.', category: 'Philosophy' },
  { text: 'Doubt is more valuable than certainty.', category: 'Philosophy' },
  { text: 'Loyalty should have limits.', category: 'Philosophy' },
  { text: 'Humility is the hardest virtue to practice.', category: 'Philosophy' },
  { text: 'The relationships you keep say more about you than the achievements you chase.', category: 'Philosophy' },
  { text: 'Pain teaches more effectively than pleasure does.', category: 'Philosophy' },
  { text: 'Choosing not to choose is still a choice with consequences.', category: 'Philosophy' },
  { text: 'Authenticity matters more than likability.', category: 'Philosophy' },
  { text: 'A good question is more valuable than a good answer.', category: 'Philosophy' },

  // Politics (39)
  { text: 'Voting should be mandatory for every citizen.', category: 'Politics' },
  { text: 'Term limits should apply to every elected office.', category: 'Politics' },
  { text: 'The two-party system is broken beyond repair.', category: 'Politics' },
  { text: 'Social media has done more harm than good for democracy.', category: 'Politics' },
  { text: 'Politicians should be banned from owning individual stocks.', category: 'Politics' },
  { text: 'The voting age should be raised to 21.', category: 'Politics' },
  { text: 'Ranked-choice voting should be adopted nationwide.', category: 'Politics' },
  { text: 'The Supreme Court should have term limits.', category: 'Politics' },
  { text: 'Every citizen should serve one year of public service.', category: 'Politics' },
  { text: 'Lobbying should be illegal.', category: 'Politics' },
  { text: 'Political ads on social media should be banned.', category: 'Politics' },
  { text: 'The minimum wage should be tied to inflation automatically.', category: 'Politics' },
  { text: 'Borders are an outdated concept in the modern world.', category: 'Politics' },
  { text: 'Prisons should focus on rehabilitation, not punishment.', category: 'Politics' },
  { text: 'The death penalty should be abolished worldwide.', category: 'Politics' },
  { text: 'Foreign aid should be redirected to domestic problems.', category: 'Politics' },
  { text: 'All elections should be publicly funded.', category: 'Politics' },
  { text: 'Direct democracy works better than representative democracy at small scales.', category: 'Politics' },
  { text: 'Political parties should be dissolved entirely.', category: 'Politics' },
  { text: 'Local elections deserve as much media attention as national ones.', category: 'Politics' },
  { text: 'Election day should be a national holiday.', category: 'Politics' },
  { text: 'Political campaigns should have strict spending limits.', category: 'Politics' },
  { text: 'Judges should be appointed, not elected.', category: 'Politics' },
  { text: 'Gerrymandering should be handled by independent, non-partisan commissions.', category: 'Politics' },
  { text: 'Citizens should be able to recall elected officials more easily.', category: 'Politics' },
  { text: 'Public trust in government is lower today mostly because of transparency failures, not policy failures.', category: 'Politics' },
  { text: 'Civic education should be mandatory before high school graduation.', category: 'Politics' },
  { text: 'Political debates should be moderated by AI to reduce bias.', category: 'Politics' },
  { text: 'Whistleblowers deserve stronger legal protection than they currently get.', category: 'Politics' },
  { text: 'Government budgets should be easier for the average citizen to understand.', category: 'Politics' },
  { text: 'Local government has more influence on daily life than most people realize.', category: 'Politics' },
  { text: 'Term limits for unelected government advisors would improve accountability.', category: 'Politics' },
  { text: 'Online voting would increase turnout enough to be worth the security risk.', category: 'Politics' },
  { text: 'Public officials should be required to hold regular town halls.', category: 'Politics' },
  { text: 'Referendums should be used more often to decide major national issues.', category: 'Politics' },
  { text: 'Campaign donations should be capped regardless of the source.', category: 'Politics' },
  { text: 'Government transparency laws should apply equally to every branch.', category: 'Politics' },
  { text: 'Redistricting should happen more frequently than once a decade.', category: 'Politics' },
  { text: 'Public servants should face harsher penalties for corruption than private citizens do.', category: 'Politics' },

  // Health (38)
  { text: 'Losing weight using Ozempic is not the same as losing weight through diet and exercise.', category: 'Health' },
  { text: 'Therapy should be free.', category: 'Health' },
  { text: 'Mental health days should be treated the same as sick days.', category: 'Health' },
  { text: 'A vegan diet is healthier than a meat-based one.', category: 'Health' },
  { text: 'Fitness influencers do more harm than good.', category: 'Health' },
  { text: 'The eight-hour sleep rule is overrated.', category: 'Health' },
  { text: 'Recreational marijuana should be legal everywhere.', category: 'Health' },
  { text: 'Health insurance should not be tied to employment.', category: 'Health' },
  { text: 'Cosmetic surgery on minors should be banned.', category: 'Health' },
  { text: 'Energy drinks should be banned for anyone under eighteen.', category: 'Health' },
  { text: 'Modern medicine over-prescribes antidepressants.', category: 'Health' },
  { text: 'Drinking alcohol is worse for you than smoking weed.', category: 'Health' },
  { text: 'Walking ten thousand steps a day is a marketing myth.', category: 'Health' },
  { text: 'All packaged foods should be required to display a health rating.', category: 'Health' },
  { text: 'Universal healthcare is a basic human right.', category: 'Health' },
  { text: 'Multivitamins are mostly a waste of money for healthy adults.', category: 'Health' },
  { text: 'Sleep tracking apps create more anxiety than they solve.', category: 'Health' },
  { text: 'Fasting diets are more hype than science.', category: 'Health' },
  { text: 'Cold plunges are more placebo than real physical benefit.', category: 'Health' },
  { text: 'Doctors should be required to explain treatment costs before prescribing them.', category: 'Health' },
  { text: 'Preventive care should be fully covered by every insurance plan.', category: 'Health' },
  { text: 'Burnout should be treated as a medical condition, not a personal failing.', category: 'Health' },
  { text: 'Sugar should be regulated like tobacco.', category: 'Health' },
  { text: 'Wearing sunscreen daily matters more than most people realize.', category: 'Health' },
  { text: 'Gyms overcomplicate what it actually takes to get fit.', category: 'Health' },
  { text: 'Mental health screenings should be part of every annual physical.', category: 'Health' },
  { text: 'Fad diets do more harm than the weight they claim to help you lose.', category: 'Health' },
  { text: 'Hospitals should be required to post prices for common procedures publicly.', category: 'Health' },
  { text: 'Skipping breakfast is not as harmful as it\'s made out to be.', category: 'Health' },
  { text: 'Telehealth appointments are just as effective as in-person visits for most concerns.', category: 'Health' },
  { text: 'Protein supplements are overused by people who don\'t need them.', category: 'Health' },
  { text: 'Chronic stress does more long-term damage than a poor diet.', category: 'Health' },
  { text: 'Standing desks are more marketing than meaningful health benefit.', category: 'Health' },
  { text: 'Health class in school should include mental health, not just physical health.', category: 'Health' },
  { text: 'Painkiller dependency starts more often with legal prescriptions than illegal drugs.', category: 'Health' },
  { text: 'Annual physicals catch fewer problems than people assume.', category: 'Health' },
  { text: 'A four-day work week would improve public health more than any wellness program.', category: 'Health' },
  { text: 'Elective surgery should require a mandatory waiting period.', category: 'Health' },

  // Environment (35)
  { text: 'Air travel should be limited to a few flights per person per year.', category: 'Environment' },
  { text: 'Nuclear energy is the only realistic path to zero emissions.', category: 'Environment' },
  { text: 'Single-use plastic packaging should be banned by 2030.', category: 'Environment' },
  { text: 'Climate change is the most important issue of the next 20 years.', category: 'Environment' },
  { text: 'Cars should be banned from city centers.', category: 'Environment' },
  { text: 'Recycling, as currently practiced, is mostly a scam.', category: 'Environment' },
  { text: 'Lawns should be banned in drought-prone areas.', category: 'Environment' },
  { text: 'Fast fashion should be regulated out of existence.', category: 'Environment' },
  { text: 'Bottled water should be banned wherever tap water is safe.', category: 'Environment' },
  { text: 'Cruise ships should be banned for environmental reasons.', category: 'Environment' },
  { text: 'Owning more than one car per household should be taxed heavily.', category: 'Environment' },
  { text: 'National parks should be off-limits to private vehicles.', category: 'Environment' },
  { text: 'Companies that pollute should be charged for ecosystem damage.', category: 'Environment' },
  { text: 'Going paperless saves more trees than recycling ever will.', category: 'Environment' },
  { text: 'Meat consumption should be taxed to reflect its environmental cost.', category: 'Environment' },
  { text: 'Every new building should be required to include solar panels.', category: 'Environment' },
  { text: 'Composting should be mandatory in cities with curbside collection.', category: 'Environment' },
  { text: 'Fast delivery culture is worse for the environment than people admit.', category: 'Environment' },
  { text: 'Golf courses use more water than they\'re worth in drought-prone regions.', category: 'Environment' },
  { text: 'Carbon offsets are more marketing than measurable impact.', category: 'Environment' },
  { text: 'Public transit should be free to reduce car dependency.', category: 'Environment' },
  { text: 'Zoos and aquariums do more for conservation than critics give them credit for.', category: 'Environment' },
  { text: 'Electric vehicles are not as clean as they\'re marketed to be once production is factored in.', category: 'Environment' },
  { text: 'Every new home should be required to include a rainwater collection system.', category: 'Environment' },
  { text: 'Reforestation efforts matter more than reducing emissions in the short term.', category: 'Environment' },
  { text: 'Packaging waste is a bigger problem than plastic straws ever were.', category: 'Environment' },
  { text: 'Space tourism is an unjustifiable waste of resources given its environmental cost.', category: 'Environment' },
  { text: 'Urban green spaces should be prioritized over parking lots in every new development'}
]