// src/features/recordings/topics.data.js
//
// Static topics, tagged by category — spinning happens entirely
// client-side. Backend just receives whichever `text` string is picked
// as `topic` on recording creation, nothing category-related is sent.
//
// Categories are grouped into two collections shown as a switcher on
// RecorderScreen: 'everyday' (light/casual) and 'thoughtful' (serious/
// debate-style). CATEGORY_TO_COLLECTION is the source of truth for that
// grouping — add new categories to it, or the sanity check below throws.

export const CATEGORY_TO_COLLECTION = {
  'Everyday Life': 'everyday',
  'Fun': 'everyday',
  'Culture': 'everyday',
  'Sports': 'everyday',
  'Health': 'everyday',
  'Philosophy': 'thoughtful',
  'Opinion': 'thoughtful',
  'Current Affairs': 'thoughtful',
  'Technology': 'thoughtful',
  'Business': 'thoughtful',
  'Education': 'thoughtful',
  'Politics': 'thoughtful',
  'Environment': 'thoughtful',
};

export const COLLECTIONS = ['everyday', 'thoughtful'];

export const CATEGORIES = Object.keys(CATEGORY_TO_COLLECTION);

export const TOPICS = [
  { text: 'My relationship with chai', category: 'Everyday Life' },
  { text: 'The one Indian habit I want the world to adopt', category: 'Everyday Life' },
  { text: 'Living in a joint family', category: 'Everyday Life' },
  { text: 'Living in a nuclear family', category: 'Everyday Life' },
  { text: 'The pressure of "log kya kahenge"', category: 'Everyday Life' },
  { text: 'My first independent trip in India', category: 'Everyday Life' },
  { text: 'Why I love/hate Indian summers', category: 'Everyday Life' },
  { text: 'The best street food in my city', category: 'Everyday Life' },
  { text: 'A festival that still feels magical', category: 'Everyday Life' },
  { text: 'My honest opinion about Indian weddings', category: 'Everyday Life' },
  { text: 'The art of bargaining in Indian markets', category: 'Everyday Life' },
  { text: 'Why every Indian has a "relative in government"', category: 'Everyday Life' },
  { text: 'My experience with Indian railways', category: 'Everyday Life' },
  { text: 'The great Indian power cut', category: 'Everyday Life' },
  { text: 'Why we still use "ji" so much', category: 'Everyday Life' },
  { text: 'A childhood game I still remember', category: 'Everyday Life' },
  { text: 'My relationship with my mother tongue', category: 'Everyday Life' },
  { text: 'The first time I cooked for my family', category: 'Everyday Life' },
  { text: 'Why Indian parents compare children', category: 'Everyday Life' },
  { text: 'A family tradition I want to continue', category: 'Everyday Life' },
  { text: 'The pressure of being the "ideal" child', category: 'Everyday Life' },
  { text: 'My experience with arranged marriage conversations', category: 'Everyday Life' },
  { text: 'Why we overfeed guests', category: 'Everyday Life' },
  { text: 'The Indian way of saying "I\'ll come in 10 minutes"', category: 'Everyday Life' },
  { text: 'My favourite season in India and why', category: 'Everyday Life' },
  { text: 'A local market I love', category: 'Everyday Life' },
  { text: 'Why we still prefer cash sometimes', category: 'Everyday Life' },
  { text: 'The joy of monsoon in my city', category: 'Everyday Life' },
  { text: 'A neighbour story I\'ll never forget', category: 'Everyday Life' },
  { text: 'Why Indian homes always have extra food', category: 'Everyday Life' },
  { text: 'My relationship with auto-rickshaw drivers', category: 'Everyday Life' },
  { text: 'The best advice an elder gave me', category: 'Everyday Life' },
  { text: 'Why we still touch feet', category: 'Everyday Life' },
  { text: 'A time I felt proud to be Indian', category: 'Everyday Life' },
  { text: 'My honest take on Indian traffic', category: 'Everyday Life' },
  { text: 'Why we love free advice', category: 'Everyday Life' },
  { text: 'The Indian concept of "adjust"', category: 'Everyday Life' },
  { text: 'A small town vs big city life', category: 'Everyday Life' },
  { text: 'Why we still ask about salary', category: 'Everyday Life' },
  { text: 'My experience with Indian customer service', category: 'Everyday Life' },
  { text: 'The pressure of owning a house', category: 'Everyday Life' },
  { text: 'Why we celebrate everything with food', category: 'Everyday Life' },
  { text: 'A relative I find most interesting', category: 'Everyday Life' },
  { text: 'The Indian habit of saving everything', category: 'Everyday Life' },
  { text: 'Why we still believe in "shubh muhurat"', category: 'Everyday Life' },
  { text: 'My relationship with WhatsApp family groups', category: 'Everyday Life' },
  { text: 'The best thing about Indian hospitality', category: 'Everyday Life' },
  { text: 'Why we say "it\'s okay" even when it\'s not', category: 'Everyday Life' },
  { text: 'A childhood fear I still remember', category: 'Everyday Life' },
  { text: 'Why Indian mothers are the original multitaskers', category: 'Everyday Life' },
  { text: 'The joy of finding a good PG', category: 'Everyday Life' },
  { text: 'My experience with Indian banking', category: 'Everyday Life' },
  { text: 'Why we still gift silver coins', category: 'Everyday Life' },
  { text: 'A time I missed home badly', category: 'Everyday Life' },
  { text: 'The Indian way of showing care', category: 'Everyday Life' },
  { text: 'Why we love long conversations', category: 'Everyday Life' },
  { text: 'My honest opinion about Indian cinema', category: 'Everyday Life' },
  { text: 'A festival I don\'t enjoy and why', category: 'Everyday Life' },
  { text: 'Why we still write "Respected Sir/Madam"', category: 'Everyday Life' },
  { text: 'The one thing I want to change about daily Indian life', category: 'Everyday Life' },
  { text: 'Coaching culture in India', category: 'Education' },
  { text: 'Board exams pressure', category: 'Education' },
  { text: 'Why marks still matter too much', category: 'Education' },
  { text: 'Online learning vs offline learning', category: 'Education' },
  { text: 'The Indian education system\'s biggest flaw', category: 'Education' },
  { text: 'Why we still memorise instead of understanding', category: 'Education' },
  { text: 'My experience with competitive exams', category: 'Education' },
  { text: 'Is the Indian education system preparing us for life?', category: 'Education' },
  { text: 'Why students fear failure so much', category: 'Education' },
  { text: 'The role of tuition in Indian student life', category: 'Education' },
  { text: 'Should homework be reduced?', category: 'Education' },
  { text: 'Why English is still a status symbol', category: 'Education' },
  { text: 'My honest opinion about college life in India', category: 'Education' },
  { text: 'The pressure of choosing science', category: 'Education' },
  { text: 'Why we need more skill-based education', category: 'Education' },
  { text: 'Campus placements: fair or stressful?', category: 'Education' },
  { text: 'The gap between degree and job skills', category: 'Education' },
  { text: 'Why Indian students study abroad', category: 'Education' },
  { text: 'Is ranking system healthy?', category: 'Education' },
  { text: 'My experience with group projects', category: 'Education' },
  { text: 'Why we need financial education in schools', category: 'Education' },
  { text: 'The real purpose of education', category: 'Education' },
  { text: 'Should coding be compulsory?', category: 'Education' },
  { text: 'Why students struggle with public speaking', category: 'Education' },
  { text: 'My favourite teacher and why', category: 'Education' },
  { text: 'The pressure of being a topper', category: 'Education' },
  { text: 'Why we still have rote learning', category: 'Education' },
  { text: 'Online degrees vs traditional degrees', category: 'Education' },
  { text: 'Should attendance be compulsory?', category: 'Education' },
  { text: 'The role of parents in career decisions', category: 'Education' },
  { text: 'Why competition among students is toxic', category: 'Education' },
  { text: 'My experience with online classes', category: 'Education' },
  { text: 'Should exams be open-book?', category: 'Education' },
  { text: 'The importance of extracurricular activities', category: 'Education' },
  { text: 'Why we need better career counselling', category: 'Education' },
  { text: 'Is college necessary for success?', category: 'Education' },
  { text: 'The pressure of engineering/medical', category: 'Education' },
  { text: 'Why students join multiple courses', category: 'Education' },
  { text: 'My honest take on Indian universities', category: 'Education' },
  { text: 'What I wish schools taught more', category: 'Education' },
  { text: 'The real meaning of "jugaad" at work', category: 'Business' },
  { text: 'Why most meetings can be emails', category: 'Business' },
  { text: 'Work from home vs office in India', category: 'Business' },
  { text: 'The pressure of "stable job"', category: 'Business' },
  { text: 'Handling "kya package mila?" questions', category: 'Business' },
  { text: 'Is Indian startup culture healthy?', category: 'Business' },
  { text: 'Why we still value government jobs', category: 'Business' },
  { text: 'My experience with office politics', category: 'Business' },
  { text: 'The Indian way of giving feedback', category: 'Business' },
  { text: 'Why we struggle with work-life balance', category: 'Business' },
  { text: 'Is hustle culture overrated?', category: 'Business' },
  { text: 'The pressure of switching jobs', category: 'Business' },
  { text: 'Why we still ask for "reference"', category: 'Business' },
  { text: 'My honest opinion about corporate life', category: 'Business' },
  { text: 'The gap between salary and expenses', category: 'Business' },
  { text: 'Why soft skills matter more than hard skills', category: 'Business' },
  { text: 'Handling difficult bosses', category: 'Business' },
  { text: 'The Indian concept of "loyalty" to company', category: 'Business' },
  { text: 'Why we fear asking for a raise', category: 'Business' },
  { text: 'Is freelancing better than a job?', category: 'Business' },
  { text: 'The pressure of LinkedIn success stories', category: 'Business' },
  { text: 'Why we still work long hours', category: 'Business' },
  { text: 'My experience with first job', category: 'Business' },
  { text: 'Should salary be transparent?', category: 'Business' },
  { text: 'The real cost of unpaid internships', category: 'Business' },
  { text: 'Why teamwork is hard in Indian offices', category: 'Business' },
  { text: 'Handling family pressure about career', category: 'Business' },
  { text: 'Is entrepreneurship realistic for everyone?', category: 'Business' },
  { text: 'The importance of communication at work', category: 'Business' },
  { text: 'Why we struggle with saying "no"', category: 'Business' },
  { text: 'My honest take on appraisals', category: 'Business' },
  { text: 'The pressure of upskilling constantly', category: 'Business' },
  { text: 'Why job security still matters', category: 'Business' },
  { text: 'Working under a micromanager', category: 'Business' },
  { text: 'The Indian way of celebrating success at work', category: 'Business' },
  { text: 'Why we still need better HR policies', category: 'Business' },
  { text: 'My experience with remote work', category: 'Business' },
  { text: 'Is passion enough for a career?', category: 'Business' },
  { text: 'The pressure of being the sole earner', category: 'Business' },
  { text: 'Why networking feels awkward', category: 'Business' },
  { text: 'Handling office favouritism', category: 'Business' },
  { text: 'The real meaning of "growth" in a job', category: 'Business' },
  { text: 'Why we stay in toxic jobs', category: 'Business' },
  { text: 'My experience with interviews', category: 'Business' },
  { text: 'Should notice periods be shorter?', category: 'Business' },
  { text: 'The pressure of side hustles', category: 'Business' },
  { text: 'Why we need better mentorship', category: 'Business' },
  { text: 'Is 9-5 outdated?', category: 'Business' },
  { text: 'The Indian dream of becoming a manager', category: 'Business' },
  { text: 'What I learned from my worst job', category: 'Business' },
  { text: 'Why soft skills decide promotions', category: 'Business' },
  { text: 'Handling salary negotiations', category: 'Business' },
  { text: 'The future of work in India', category: 'Business' },
  { text: 'Why we still fear failure at work', category: 'Business' },
  { text: 'My definition of career success', category: 'Business' },
  { text: 'Reservation: still needed or time to change?', category: 'Culture' },
  { text: 'Why public cleanliness is still a challenge', category: 'Culture' },
  { text: 'Social media vs real life in Indian cities', category: 'Culture' },
  { text: 'Arranged marriage in 2026', category: 'Culture' },
  { text: 'The rise of coaching centres', category: 'Culture' },
  { text: 'Is English still a status symbol?', category: 'Culture' },
  { text: 'Why we struggle with civic sense', category: 'Culture' },
  { text: 'The influence of Bollywood on society', category: 'Culture' },
  { text: 'Why caste still matters', category: 'Culture' },
  { text: 'Women safety in Indian cities', category: 'Culture' },
  { text: 'The pressure of marriage after a certain age', category: 'Culture' },
  { text: 'Why we still have gender roles', category: 'Culture' },
  { text: 'The impact of WhatsApp universities', category: 'Culture' },
  { text: 'Is India becoming less tolerant?', category: 'Culture' },
  { text: 'Why we love free advice from everyone', category: 'Culture' },
  { text: 'The changing definition of success', category: 'Culture' },
  { text: 'Why mental health is still taboo', category: 'Culture' },
  { text: 'The role of religion in daily life', category: 'Culture' },
  { text: 'Why we still prefer sons in some families', category: 'Culture' },
  { text: 'The impact of urbanisation', category: 'Culture' },
  { text: 'Why we struggle with traffic rules', category: 'Culture' },
  { text: 'The culture of "adjust"', category: 'Culture' },
  { text: 'Is joint family system dying?', category: 'Culture' },
  { text: 'Why we still fear "log kya kahenge"', category: 'Culture' },
  { text: 'The rise of dating apps in India', category: 'Culture' },
  { text: 'Why we over-celebrate celebrities', category: 'Culture' },
  { text: 'The impact of short-form content', category: 'Culture' },
  { text: 'Why we still have dowry in some places', category: 'Culture' },
  { text: 'The changing role of women', category: 'Culture' },
  { text: 'Why we struggle with public transport', category: 'Culture' },
  { text: 'The culture of comparison', category: 'Culture' },
  { text: 'Is patriotism only about cricket?', category: 'Culture' },
  { text: 'Why we still need better sex education', category: 'Culture' },
  { text: 'The impact of migration to cities', category: 'Culture' },
  { text: 'Why we love conspiracy theories', category: 'Culture' },
  { text: 'The role of elders in modern families', category: 'Culture' },
  { text: 'Why we still have child labour', category: 'Culture' },
  { text: 'The pressure of social media validation', category: 'Culture' },
  { text: 'Is Indian society becoming individualistic?', category: 'Culture' },
  { text: 'Why we struggle with honesty in public life', category: 'Culture' },
  { text: 'The culture of "chalta hai"', category: 'Culture' },
  { text: 'Why we still respect age more than merit', category: 'Culture' },
  { text: 'The impact of OTT on Indian families', category: 'Culture' },
  { text: 'Why we fear speaking against the majority', category: 'Culture' },
  { text: 'My vision for a better Indian society', category: 'Culture' },
  { text: 'Why civic sense starts at home', category: 'Culture' },
  { text: 'The real meaning of unity in diversity', category: 'Culture' },
  { text: 'Why we need more open conversations', category: 'Culture' },
  { text: 'The changing face of Indian youth', category: 'Culture' },
  { text: 'Why we still struggle with equality', category: 'Culture' },
  { text: 'Cricket is overrated in India', category: 'Opinion' },
  { text: 'Should voting be compulsory?', category: 'Opinion' },
  { text: 'Are Indian parents too involved in careers?', category: 'Opinion' },
  { text: 'UPI has changed India more than most schemes', category: 'Opinion' },
  { text: 'Can India become developed by 2047?', category: 'Opinion' },
  { text: 'Is the Indian media biased?', category: 'Opinion' },
  { text: 'Should private schools be more regulated?', category: 'Opinion' },
  { text: 'Are competitive exams fair?', category: 'Opinion' },
  { text: 'Is the startup ecosystem overhyped?', category: 'Opinion' },
  { text: 'Should we ban fireworks during Diwali?', category: 'Opinion' },
  { text: 'Is English education creating a class divide?', category: 'Opinion' },
  { text: 'Are reality shows harming youth?', category: 'Opinion' },
  { text: 'Should government jobs have age limits?', category: 'Opinion' },
  { text: 'Is social media making us lonely?', category: 'Opinion' },
  { text: 'Should there be a wealth tax?', category: 'Opinion' },
  { text: 'Are Indian cities becoming unlivable?', category: 'Opinion' },
  { text: 'Is the education system outdated?', category: 'Opinion' },
  { text: 'Should we have stricter traffic laws?', category: 'Opinion' },
  { text: 'Are influencers overrated?', category: 'Opinion' },
  { text: 'Is hustle culture toxic?', category: 'Opinion' },
  { text: 'Should college degrees be optional?', category: 'Opinion' },
  { text: 'Are Indian weddings too expensive?', category: 'Opinion' },
  { text: 'Is patriotism being misused?', category: 'Opinion' },
  { text: 'Should we have population control policies?', category: 'Opinion' },
  { text: 'Are public sector companies inefficient?', category: 'Opinion' },
  { text: 'Is the Indian film industry stuck?', category: 'Opinion' },
  { text: 'Should junk food advertising be restricted?', category: 'Opinion' },
  { text: 'Are entrance exams necessary?', category: 'Opinion' },
  { text: 'Is remote work killing office culture?', category: 'Opinion' },
  { text: 'Should there be a uniform civil code?', category: 'Opinion' },
  { text: 'Are Indian men changing enough?', category: 'Opinion' },
  { text: 'Is the stock market gambling for most people?', category: 'Opinion' },
  { text: 'Should political parties be more transparent?', category: 'Opinion' },
  { text: 'Are we too obsessed with rankings?', category: 'Opinion' },
  { text: 'Is free speech under threat?', category: 'Opinion' },
  { text: 'Should there be a limit on campaign spending?', category: 'Opinion' },
  { text: 'Are Indian startups solving real problems?', category: 'Opinion' },
  { text: 'Is the middle class being squeezed?', category: 'Opinion' },
  { text: 'Should we have better data privacy laws?', category: 'Opinion' },
  { text: 'Is religion being used for politics?', category: 'Opinion' },
  { text: 'Are we losing our local languages?', category: 'Opinion' },
  { text: 'Should public transport be free?', category: 'Opinion' },
  { text: 'Is the Indian bureaucracy too slow?', category: 'Opinion' },
  { text: 'Are we celebrating mediocrity?', category: 'Opinion' },
  { text: 'My most unpopular opinion about India', category: 'Opinion' },
  { text: 'If I could ban one thing in India for a day', category: 'Fun' },
  { text: 'Roast the Indian railway ticket booking experience', category: 'Fun' },
  { text: 'Why every Indian has a "relative in government"', category: 'Fun' },
  { text: 'The great Indian traffic negotiation', category: 'Fun' },
  { text: 'My honest opinion about Indian web series', category: 'Fun' },
  { text: 'If animals could speak Hindi', category: 'Fun' },
  { text: 'Sell a broken umbrella in monsoon', category: 'Fun' },
  { text: 'Why Indian mothers never throw anything', category: 'Fun' },
  { text: 'The secret life of a pressure cooker', category: 'Fun' },
  { text: 'If I were the traffic police for a day', category: 'Fun' },
  { text: 'Roast Indian customer care calls', category: 'Fun' },
  { text: 'Why we still write "do the needful"', category: 'Fun' },
  { text: 'The Indian way of giving directions', category: 'Fun' },
  { text: 'If I could redesign Indian weddings', category: 'Fun' },
  { text: 'Why we love free samples', category: 'Fun' },
  { text: 'The drama of Indian power cuts', category: 'Fun' },
  { text: 'If chai disappeared for a week', category: 'Fun' },
  { text: 'Roast the "quick 5-minute" Indian meeting', category: 'Fun' },
  { text: 'Why we still use "as per my knowledge"', category: 'Fun' },
  { text: 'The Indian family WhatsApp group chaos', category: 'Fun' },
  { text: 'If I could invent a new Indian festival', category: 'Fun' },
  { text: 'Why we bargain even for fixed price', category: 'Fun' },
  { text: 'The art of saying "I\'ll think about it"', category: 'Fun' },
  { text: 'If I were a street food vendor', category: 'Fun' },
  { text: 'Roast Indian online delivery excuses', category: 'Fun' },
  { text: 'Why we still say "first class"', category: 'Fun' },
  { text: 'The Indian concept of "timepass"', category: 'Fun' },
  { text: 'If I could make one law for a day', category: 'Fun' },
  { text: 'Why we love long wedding functions', category: 'Fun' },
  { text: 'The drama of finding parking', category: 'Fun' },
  { text: 'If I could rename Indian cities', category: 'Fun' },
  { text: 'Why we still use "kindly" everywhere', category: 'Fun' },
  { text: 'The Indian way of showing anger', category: 'Fun' },
  { text: 'If I were the weather for a day', category: 'Fun' },
  { text: 'Roast Indian reality TV', category: 'Fun' },
  { text: 'Why we still ask "have you eaten?"', category: 'Fun' },
  { text: 'The secret behind Indian "5 minutes"', category: 'Fun' },
  { text: 'If I could ban one emoji', category: 'Fun' },
  { text: 'Why we love dramatic serials', category: 'Fun' },
  { text: 'My funniest Indian travel story', category: 'Fun' },
  { text: 'What does freedom mean to me?', category: 'Philosophy' },
  { text: 'The meaning of success in Indian society', category: 'Philosophy' },
  { text: 'Is happiness a choice?', category: 'Philosophy' },
  { text: 'The cost of comparison', category: 'Philosophy' },
  { text: 'What makes a person truly educated?', category: 'Philosophy' },
  { text: 'The value of silence', category: 'Philosophy' },
  { text: 'Is failure necessary?', category: 'Philosophy' },
  { text: 'The difference between confidence and ego', category: 'Philosophy' },
  { text: 'What I want to be remembered for', category: 'Philosophy' },
  { text: 'The role of courage in daily life', category: 'Philosophy' },
  { text: 'Is comfort the enemy of growth?', category: 'Philosophy' },
  { text: 'The meaning of respect', category: 'Philosophy' },
  { text: 'Why we fear judgement', category: 'Philosophy' },
  { text: 'The power of small habits', category: 'Philosophy' },
  { text: 'What true independence means', category: 'Philosophy' },
  { text: 'The weight of expectations', category: 'Philosophy' },
  { text: 'Is ambition always good?', category: 'Philosophy' },
  { text: 'The meaning of home', category: 'Philosophy' },
  { text: 'Why we need more empathy', category: 'Philosophy' },
  { text: 'The difference between knowledge and wisdom', category: 'Philosophy' },
  { text: 'What makes life meaningful?', category: 'Philosophy' },
  { text: 'The courage to be average', category: 'Philosophy' },
  { text: 'Why we chase validation', category: 'Philosophy' },
  { text: 'The value of time', category: 'Philosophy' },
  { text: 'What I have unlearned', category: 'Philosophy' },
  { text: 'The meaning of simplicity', category: 'Philosophy' },
  { text: 'Why we resist change', category: 'Philosophy' },
  { text: 'The power of listening', category: 'Philosophy' },
  { text: 'What freedom of speech means to me', category: 'Philosophy' },
  { text: 'The quiet strength of ordinary people', category: 'Philosophy' },
  { text: 'India\'s space achievements and what they mean', category: 'Current Affairs' },
  { text: 'The impact of UPI on daily life', category: 'Current Affairs' },
  { text: 'Is Digital India working?', category: 'Current Affairs' },
  { text: 'The future of electric vehicles in India', category: 'Current Affairs' },
  { text: 'Why local manufacturing matters', category: 'Current Affairs' },
  { text: 'The challenge of unemployment', category: 'Current Affairs' },
  { text: 'Is the gig economy good for youth?', category: 'Current Affairs' },
  { text: 'The rise of Indian startups', category: 'Current Affairs' },
  { text: 'Why healthcare access is still unequal', category: 'Current Affairs' },
  { text: 'The future of Indian agriculture', category: 'Current Affairs' },
  { text: 'Is the New Education Policy effective?', category: 'Current Affairs' },
  { text: 'Why we need better public transport', category: 'Current Affairs' },
  { text: 'The impact of climate change on Indian cities', category: 'Current Affairs' },
  { text: 'Why water conservation is urgent', category: 'Current Affairs' },
  { text: 'The role of youth in politics', category: 'Current Affairs' },
  { text: 'Is social media regulation needed?', category: 'Current Affairs' },
  { text: 'The future of work in Tier-2 and Tier-3 cities', category: 'Current Affairs' },
  { text: 'Why mental health infrastructure is lacking', category: 'Current Affairs' },
  { text: 'The impact of short videos on attention span', category: 'Current Affairs' },
  { text: 'Is India ready for AI revolution?', category: 'Current Affairs' },
  { text: 'Why financial literacy is still low', category: 'Current Affairs' },
  { text: 'The challenge of plastic pollution', category: 'Current Affairs' },
  { text: 'Why women\'s workforce participation is low', category: 'Current Affairs' },
  { text: 'The future of Indian tourism', category: 'Current Affairs' },
  { text: 'Is the startup funding winter over?', category: 'Current Affairs' },
  { text: 'Why we need better disaster management', category: 'Current Affairs' },
  { text: 'The role of regional languages in tech', category: 'Current Affairs' },
  { text: 'Why civic participation is low', category: 'Current Affairs' },
  { text: 'The impact of rising fuel prices', category: 'Current Affairs' },
  { text: 'Why we need more green spaces in cities', category: 'Current Affairs' },
  { text: 'The future of Indian cricket beyond stars', category: 'Current Affairs' },
  { text: 'Is the middle class shrinking?', category: 'Current Affairs' },
  { text: 'Why skilling programmes matter', category: 'Current Affairs' },
  { text: 'The challenge of fake news', category: 'Current Affairs' },
  { text: 'Why rural India still faces digital divide', category: 'Current Affairs' },
  { text: 'The future of electric public transport', category: 'Current Affairs' },
  { text: 'Why we need better urban planning', category: 'Current Affairs' },
  { text: 'The impact of climate migration', category: 'Current Affairs' },
  { text: 'Why youth entrepreneurship needs support', category: 'Current Affairs' },
  { text: 'My vision for India in 2047', category: 'Current Affairs' },
  { text: 'AI will replace most software engineers within ten years.', category: 'Technology' },
  { text: 'Smartphones have made us less social, not more.', category: 'Technology' },
  { text: 'Self-driving cars should be the norm once they\'re proven safer than humans.', category: 'Technology' },
  { text: 'Tech companies should be banned from selling personal data.', category: 'Technology' },
  { text: 'Cryptocurrency will eventually replace traditional money.', category: 'Technology' },
  { text: 'Children under thirteen should not be allowed on social media.', category: 'Technology' },
  { text: 'Algorithms shape your opinions more than your friends do.', category: 'Technology' },
  { text: 'Open source software has done more for humanity than any tech company.', category: 'Technology' },
  { text: 'Smart speakers in the home are a privacy disaster waiting to happen.', category: 'Technology' },
  { text: 'VR will eventually replace most travel.', category: 'Technology' },
  { text: 'Coding should be a required class in high school.', category: 'Technology' },
  { text: 'All bot accounts should be banned from social media.', category: 'Technology' },
  { text: 'The internet was better before algorithms took over social media.', category: 'Technology' },
  { text: 'Apps should be required to ship with a delete-my-data button.', category: 'Technology' },
  { text: 'Facial recognition in public spaces should be banned.', category: 'Technology' },
  { text: 'Recording people using smart glasses in public spaces should be banned.', category: 'Technology' },
  { text: 'Big tech companies are more powerful than most governments.', category: 'Technology' },
  { text: 'The smartphone has done more harm to teenagers than alcohol.', category: 'Technology' },
  { text: 'Wearable health trackers do more harm than good.', category: 'Technology' },
  { text: 'Passwords will be obsolete within the next decade.', category: 'Technology' },
  { text: 'Everyone should use a password manager.', category: 'Technology' },
  { text: 'Video calls have made people worse at reading body language.', category: 'Technology' },
  { text: 'E-books are better than physical books for retention.', category: 'Technology' },
  { text: 'AI-generated art should be clearly labeled as AI-made.', category: 'Technology' },
  { text: 'Right-to-repair laws should require manufacturers to sell spare parts to consumers.', category: 'Technology' },
  { text: 'Autonomous delivery drones will be commonplace within ten years.', category: 'Technology' },
  { text: 'Online anonymity does more good than harm.', category: 'Technology' },
  { text: 'Robots will eventually make better caregivers for the elderly than humans.', category: 'Technology' },
  { text: 'Every website should be required to offer a version that doesn\'t track visitors.', category: 'Technology' },
  { text: 'The next major computing platform will be wearable, not mobile.', category: 'Technology' },
  { text: 'Chatbots should be required to disclose that they are not human.', category: 'Technology' },
  { text: '3D printing will disrupt manufacturing more than the internet disrupted media.', category: 'Technology' },
  { text: 'Biometric login is safer than passwords.', category: 'Technology' },
  { text: 'AI coding assistants will make traditional computer science degrees less valuable.', category: 'Technology' },
  { text: 'Space exploration should be led by private companies, not governments.', category: 'Technology' },
  { text: 'The metaverse will never replace real-world socializing.', category: 'Technology' },
  { text: 'Encrypted messaging apps should never include a government backdoor.', category: 'Technology' },
  { text: 'Most people would be happier using a basic phone instead of a smartphone.', category: 'Technology' },
  { text: 'AI companions will become a normal part of romantic life within a generation.', category: 'Technology' },
  { text: 'Companies should be required to compensate users automatically after a data breach.', category: 'Technology' },
  { text: 'Digital minimalism is a trend that won\'t last.', category: 'Technology' },
  { text: 'Legal screen-time limits on kids\' devices would work better than relying on parents alone.', category: 'Technology' },
  { text: 'Cloud storage has made people careless about backing up their own data.', category: 'Technology' },
  { text: 'Deepfakes will make video evidence unreliable in court within ten years.', category: 'Technology' },
  { text: 'Every smart home device should have a physical off switch for its microphone.', category: 'Technology' },
  { text: 'Remote work is more productive than working in an office.', category: 'Business' },
  { text: 'Companies should be required to publish every employee\'s salary.', category: 'Business' },
  { text: 'The four-day work week should be the new standard.', category: 'Business' },
  { text: 'There are no ethical billionaires.', category: 'Business' },
  { text: 'Unpaid internships should not exist.', category: 'Business' },
  { text: 'Every big decision by a public company should be put up to a vote by shareholders.', category: 'Business' },
  { text: 'The gig economy is a step backward for labour rights.', category: 'Business' },
  { text: 'Branding has become more important than the product itself.', category: 'Business' },
  { text: 'Customer service has gotten worse in every industry over the past decade.', category: 'Business' },
  { text: 'Inheritances above a certain high threshold should face much heavier taxes.', category: 'Business' },
  { text: 'Everyone should retire at 60-65.', category: 'Business' },
  { text: 'Tipping culture has spiraled out of control.', category: 'Business' },
  { text: 'Performance reviews are a waste of time.', category: 'Business' },
  { text: 'Office dress codes are pointless in the modern era.', category: 'Business' },
  { text: 'Patents stifle innovation more than they protect it.', category: 'Business' },
  { text: 'Every job posting should be required to list its salary range.', category: 'Business' },
  { text: 'Layoffs delivered by video call or email should be illegal.', category: 'Business' },
  { text: 'Non-compete agreements should be banned.', category: 'Business' },
  { text: 'Startups fail more often from bad co-founders than bad ideas.', category: 'Business' },
  { text: 'Open-plan offices hurt productivity more than they help collaboration.', category: 'Business' },
  { text: 'Employees should be able to unionize without employer interference.', category: 'Business' },
  { text: 'A college degree should not be required for most entry-level jobs.', category: 'Business' },
  { text: 'Every company should offer more flexible leave policies.', category: 'Business' },
  { text: 'The traditional 9-to-5 workday no longer makes sense.', category: 'Business' },
  { text: 'Severance pay should be required by law after layoffs.', category: 'Business' },
  { text: 'Business ethics classes make little difference in how executives actually behave.', category: 'Business' },
  { text: 'Franchising is a better path to wealth than starting an original business.', category: 'Business' },
  { text: 'Middle management is mostly unnecessary overhead.', category: 'Business' },
  { text: 'Shareholders care too much about quarterly profits and too little about long-term growth.', category: 'Business' },
  { text: 'Small businesses deserve more tax breaks than large corporations.', category: 'Business' },
  { text: 'Job-hopping is the fastest way to grow your salary.', category: 'Business' },
  { text: 'Company loyalty is a myth that only benefits employers.', category: 'Business' },
  { text: 'Mentorship matters more than raw talent for career success.', category: 'Business' },
  { text: 'Return-to-office mandates are more about control than productivity.', category: 'Business' },
  { text: 'AI will create more jobs than it destroys.', category: 'Business' },
  { text: 'Meetings that could be an email are a bigger problem than most companies admit.', category: 'Business' },
  { text: 'Salary negotiation should be taught in every college.', category: 'Business' },
  { text: 'Employee stock options are overrated as compensation.', category: 'Business' },
  { text: 'Family businesses are harder to scale than founder-led startups.', category: 'Business' },
  { text: 'Networking matters more than credentials when it comes to getting hired.', category: 'Business' },
  { text: 'Businesses should be required to publicly disclose their environmental impact.', category: 'Business' },
  { text: 'Great leaders are made, not born.', category: 'Business' },
  { text: 'AI tutors will be better than human teachers within five years.', category: 'Education' },
  { text: 'College is the best path to success.', category: 'Education' },
  { text: 'Standardized testing is not a great way to assess a student\'s capabilities.', category: 'Education' },
  { text: 'Schools should be required to teach financial literacy.', category: 'Education' },
  { text: 'Students should be allowed to use AI while doing homework.', category: 'Education' },
  { text: 'Every student should learn how to cook before they graduate high school.', category: 'Education' },
  { text: 'Public schools should be funded more equally regardless of location.', category: 'Education' },
  { text: 'Every student should learn a second language fluently before graduating.', category: 'Education' },
  { text: 'Recess / outdoor play should be mandatory at every grade level.', category: 'Education' },
  { text: 'Teachers should be paid much more.', category: 'Education' },
  { text: 'Online learning has made students worse, not better.', category: 'Education' },
  { text: 'Required reading lists should include far more diverse voices.', category: 'Education' },
  { text: 'Mandatory school uniforms make students more equal, not less.', category: 'Education' },
  { text: 'Final exams measure memorization, not understanding.', category: 'Education' },
  { text: 'Grades do more harm than good to student motivation.', category: 'Education' },
  { text: 'Every school should offer mental health classes.', category: 'Education' },
  { text: 'Vocational / skill-based education should be marketed as equally valuable as a four-year degree.', category: 'Education' },
  { text: 'Class sizes should be capped at a reasonable number.', category: 'Education' },
  { text: 'Homework should be optional in primary school.', category: 'Education' },
  { text: 'Every student should take a public speaking class before graduating.', category: 'Education' },
  { text: 'School should start later in the day for teenagers.', category: 'Education' },
  { text: 'Cursive / handwriting skills still matter and should be taught.', category: 'Education' },
  { text: 'Group projects do more to hurt learning than help it.', category: 'Education' },
  { text: 'Attendance policies are more about compliance than actual learning.', category: 'Education' },
  { text: 'Gifted programs do more harm than good by separating students too early.', category: 'Education' },
  { text: 'Letter grades should be replaced with detailed written feedback.', category: 'Education' },
  { text: 'Every student should learn to type properly before middle school.', category: 'Education' },
  { text: 'School sports should not require a minimum GPA to participate.', category: 'Education' },
  { text: 'Teachers should be allowed to fail students for excessive absences alone.', category: 'Education' },
  { text: 'Field trips are one of the most underrated parts of education.', category: 'Education' },
  { text: 'Every school should teach media literacy as its own subject.', category: 'Education' },
  { text: 'Elite universities admit too many students based on legacy or connections.', category: 'Education' },
  { text: 'Year-round schooling would benefit students more than long summer breaks.', category: 'Education' },
  { text: 'Students should be graded on effort as much as results.', category: 'Education' },
  { text: 'Parents should have less influence over school curriculum decisions.', category: 'Education' },
  { text: 'Learning a musical instrument should be encouraged more strongly in school.', category: 'Education' },
  { text: 'Vocational skills should be taught alongside academics starting in middle school.', category: 'Education' },
  { text: 'Class rank does more to discourage students than motivate them.', category: 'Education' },
  { text: 'Every student should complete a community service project before graduating.', category: 'Education' },
  { text: 'Study abroad or exchange programs should be more accessible, not just for the wealthy.', category: 'Education' },
  { text: 'Cancel culture has gone too far.', category: 'Culture' },
  { text: 'Tipping should be abolished and replaced with higher wages.', category: 'Culture' },
  { text: 'Reality TV has done more harm than good for society.', category: 'Culture' },
  { text: 'Streaming services killed the magic of going to the movies / cinema.', category: 'Culture' },
  { text: 'Dating apps have made romance worse.', category: 'Culture' },
  { text: 'Pop music today is worse than it was twenty years ago.', category: 'Culture' },
  { text: 'Sequels, remakes and reboots prove the industry is out of ideas.', category: 'Culture' },
  { text: 'Influencer marketing has destroyed authentic recommendation.', category: 'Culture' },
  { text: 'Tattoos have lost their edge now that everyone has them.', category: 'Culture' },
  { text: 'Public libraries are the most underrated institution in society.', category: 'Culture' },
  { text: 'Modern architecture is often uglier than what it replaced.', category: 'Culture' },
  { text: 'Award shows are no longer culturally relevant.', category: 'Culture' },
  { text: 'Memes have replaced traditional satire as cultural commentary.', category: 'Culture' },
  { text: 'Reading fiction is just as valuable as reading non-fiction.', category: 'Culture' },
  { text: 'Live concerts and events are not worth the price anymore.', category: 'Culture' },
  { text: 'Podcasts have replaced books for many adults.', category: 'Culture' },
  { text: 'A lot of modern art is more hype than substance.', category: 'Culture' },
  { text: 'Short-form video is rotting attention spans across all generations.', category: 'Culture' },
  { text: 'Every adult should travel solo at least once.', category: 'Culture' },
  { text: 'Marriage as an institution is changing faster than people admit.', category: 'Culture' },
  { text: 'Nostalgia has taken over pop culture at the expense of new ideas.', category: 'Culture' },
  { text: 'Book clubs are more valuable for socializing than for actually discussing books.', category: 'Culture' },
  { text: 'Fan culture has become more toxic than supportive.', category: 'Culture' },
  { text: 'True crime content glorifies violence more than it educates.', category: 'Culture' },
  { text: 'Celebrity worship says more about us than about celebrities.', category: 'Culture' },
  { text: 'Karaoke is one of the most underrated social activities.', category: 'Culture' },
  { text: 'Museums need to modernize or risk becoming irrelevant.', category: 'Culture' },
  { text: 'Fashion trends cycle faster now because of social media, not because of creativity.', category: 'Culture' },
  { text: 'Stand-up comedy is harder to get right today than it was a decade ago.', category: 'Culture' },
  { text: 'Traveling just to say you\'ve been somewhere is different from actually experiencing a place.', category: 'Culture' },
  { text: 'Physical media like vinyl and DVDs will make a lasting comeback, not just a nostalgic blip.', category: 'Culture' },
  { text: 'Wedding costs have spiraled out of control for no good reason.', category: 'Culture' },
  { text: 'Ghosting has become an acceptable way to end relationships.', category: 'Culture' },
  { text: 'Book-to-film / series adaptations rarely capture what made the book great.', category: 'Culture' },
  { text: 'Video essays have become more insightful than traditional criticism.', category: 'Culture' },
  { text: 'Small talk is an underrated social skill, not a waste of time.', category: 'Culture' },
  { text: 'Holiday and festival traditions matter less to younger generations than they used to.', category: 'Culture' },
  { text: 'Theme parks and big entertainment venues are overpriced for what they offer today.', category: 'Culture' },
  { text: 'Autobiographies are more honest than authorized biographies.', category: 'Culture' },
  { text: 'Street art belongs in the same category as gallery art.', category: 'Culture' },
  { text: 'Binge-watching has ruined the way we experience shows.', category: 'Culture' },
  { text: 'Handwritten letters are more meaningful than any text message.', category: 'Culture' },
  { text: 'Pro athletes are paid too much for what they do.', category: 'Sports' },
  { text: 'College / university athletes should be paid fairly for their contribution.', category: 'Sports' },
  { text: 'Cricket is more skillful and strategic than many people give it credit for.', category: 'Sports' },
  { text: 'Tackling and heavy contact should be restricted in youth sports.', category: 'Sports' },
  { text: 'Instant replay has ruined the flow of live sports.', category: 'Sports' },
  { text: 'Boxing and similar combat sports should face stricter safety rules.', category: 'Sports' },
  { text: 'Many major leagues are more entertainment than pure sport at this point.', category: 'Sports' },
  { text: 'Female athletes should earn the same prize money as male athletes in comparable events.', category: 'Sports' },
  { text: 'Olympic athletes deserve far higher compensation and support than they get.', category: 'Sports' },
  { text: 'Fighting / violence in contact sports should be more tightly regulated.', category: 'Sports' },
  { text: 'Performance-enhancing drugs should be allowed in pro sports under controlled conditions.', category: 'Sports' },
  { text: 'Trash-talking is a legitimate part of competition.', category: 'Sports' },
  { text: 'Some traditional rules in older sports have outlived their usefulness.', category: 'Sports' },
  { text: 'Newer sports and formats will keep challenging older ones in popularity.', category: 'Sports' },
  { text: 'Cheerleading and similar activities should be classified as sports where appropriate.', category: 'Sports' },
  { text: 'Ultra-endurance events can be bad for long-term health if done excessively.', category: 'Sports' },
  { text: 'Sports betting has corrupted modern sports leagues.', category: 'Sports' },
  { text: 'Youth sports have become too competitive too early.', category: 'Sports' },
  { text: 'Participation trophies do more harm than good.', category: 'Sports' },
  { text: 'The Olympics should consider cost and accessibility when adding or keeping sports.', category: 'Sports' },
  { text: 'Home-field / home-crowd advantage matters more than most fans realize.', category: 'Sports' },
  { text: 'Esports deserve to be treated as seriously as traditional sports.', category: 'Sports' },
  { text: 'A salary cap or similar balance mechanism should exist in every major professional league.', category: 'Sports' },
  { text: 'Some sports take too long to hold mainstream appeal for new audiences.', category: 'Sports' },
  { text: 'Overtime and sudden-death rules often favor one side too much.', category: 'Sports' },
  { text: 'Young athletes should be allowed to profit from their name and likeness earlier.', category: 'Sports' },
  { text: 'Sports commentary has gotten worse as analytics have taken over.', category: 'Sports' },
  { text: 'High-contact sports should have stricter age limits for children.', category: 'Sports' },
  { text: 'Super teams built through free agency or auctions are bad for competitive balance.', category: 'Sports' },
  { text: 'Rivalry matches matter more to fans than championships in many cases.', category: 'Sports' },
  { text: 'Contract holdouts are justified when a player is clearly underpaid relative to the market.', category: 'Sports' },
  { text: 'Rule changes that favor scoring can change a sport for better or worse.', category: 'Sports' },
  { text: 'Extreme sports deserve more mainstream coverage.', category: 'Sports' },
  { text: 'Retired jersey numbers should be reserved for truly legendary players only.', category: 'Sports' },
  { text: 'Sports dynasties are bad for a league\'s long-term popularity.', category: 'Sports' },
  { text: 'Home teams get too much benefit of the doubt from referees / umpires.', category: 'Sports' },
  { text: 'Off-season training matters more to a player\'s career than raw talent.', category: 'Sports' },
  { text: 'Fantasy sports have changed how fans watch games - not always for the better.', category: 'Sports' },
  { text: 'Team traditions matter more to fan loyalty than a team\'s win record.', category: 'Sports' },
  { text: 'Life has no inherent meaning. We create our own purpose.', category: 'Philosophy' },
  { text: 'Free will is an illusion.', category: 'Philosophy' },
  { text: 'It\'s better to know a hard truth than a comforting lie.', category: 'Philosophy' },
  { text: 'Suffering is necessary for personal growth.', category: 'Philosophy' },
  { text: 'Happiness is a choice, not a circumstance.', category: 'Philosophy' },
  { text: 'Death is what gives life its meaning.', category: 'Philosophy' },
  { text: 'Morality is invented by humans, not discovered.', category: 'Philosophy' },
  { text: 'Time is a human construct, not a real feature of the universe.', category: 'Philosophy' },
  { text: 'A simulated existence indistinguishable from reality is just as valuable.', category: 'Philosophy' },
  { text: 'It\'s better to be a satisfied fool than a dissatisfied philosopher.', category: 'Philosophy' },
  { text: 'The ends sometimes do justify the means.', category: 'Philosophy' },
  { text: 'Solitude is more honest than community.', category: 'Philosophy' },
  { text: 'Personal identity does not survive transformation over time.', category: 'Philosophy' },
  { text: 'Forgiveness is a gift to yourself, not the other person.', category: 'Philosophy' },
  { text: 'Boredom is the root of every truly creative act.', category: 'Philosophy' },
  { text: 'Beauty is objective, not only in the eye of the beholder.', category: 'Philosophy' },
  { text: 'Fully knowing yourself is impossible.', category: 'Philosophy' },
  { text: 'Tradition is wisdom that has survived testing.', category: 'Philosophy' },
  { text: 'A life examined too closely is not worth living.', category: 'Philosophy' },
  { text: 'Kindness is a stronger foundation for a good life than intelligence.', category: 'Philosophy' },
  { text: 'Regret is more useful than people give it credit for.', category: 'Philosophy' },
  { text: 'True altruism does not exist; every good deed serves the self in some way.', category: 'Philosophy' },
  { text: 'Envy can be a productive emotion if you let it be.', category: 'Philosophy' },
  { text: 'Wisdom comes from experience, not only from books.', category: 'Philosophy' },
  { text: 'A person\'s character is best judged by how they treat strangers, not friends.', category: 'Philosophy' },
  { text: 'Curiosity matters more than discipline for a fulfilling life.', category: 'Philosophy' },
  { text: 'Silence reveals more about a person than speech does.', category: 'Philosophy' },
  { text: 'The unexamined choice is worse than the wrong choice.', category: 'Philosophy' },
  { text: 'Gratitude is a skill, not just a feeling.', category: 'Philosophy' },
  { text: 'Justice matters more than mercy.', category: 'Philosophy' },
  { text: 'A person cannot be truly free while depending on others.', category: 'Philosophy' },
  { text: 'Ambition and contentment cannot easily coexist.', category: 'Philosophy' },
  { text: 'Memory defines who we are more than our present actions do.', category: 'Philosophy' },
  { text: 'Doubt is more valuable than certainty.', category: 'Philosophy' },
  { text: 'Loyalty should have limits.', category: 'Philosophy' },
  { text: 'Humility is the hardest virtue to practice.', category: 'Philosophy' },
  { text: 'The relationships you keep say more about you than the achievements you chase.', category: 'Philosophy' },
  { text: 'Pain teaches more effectively than pleasure does.', category: 'Philosophy' },
  { text: 'Choosing not to choose is still a choice with consequences.', category: 'Philosophy' },
  { text: 'Authenticity matters more than likability.', category: 'Philosophy' },
  { text: 'A good question is more valuable than a good answer.', category: 'Philosophy' },
  { text: 'Voting should be mandatory for every eligible citizen.', category: 'Politics' },
  { text: 'Term limits should apply to every elected office.', category: 'Politics' },
  { text: 'The two-party / multi-party system as it currently works is broken beyond easy repair.', category: 'Politics' },
  { text: 'Social media has done more harm than good for democracy.', category: 'Politics' },
  { text: 'Politicians should be banned from owning individual stocks while in office.', category: 'Politics' },
  { text: 'The voting age should be raised or kept carefully considered.', category: 'Politics' },
  { text: 'Ranked-choice or preferential voting should be adopted more widely.', category: 'Politics' },
  { text: 'Higher courts should have clearer term limits or fixed tenures.', category: 'Politics' },
  { text: 'Every citizen should serve some form of public or national service.', category: 'Politics' },
  { text: 'Lobbying should be far more tightly regulated or restricted.', category: 'Politics' },
  { text: 'Political ads on social media should face much stricter rules.', category: 'Politics' },
  { text: 'The minimum wage should be tied more closely to inflation or cost of living.', category: 'Politics' },
  { text: 'Borders remain a necessary concept even in a connected world.', category: 'Politics' },
  { text: 'Prisons should focus more on rehabilitation than pure punishment.', category: 'Politics' },
  { text: 'The death penalty should be abolished or used only in the rarest cases.', category: 'Politics' },
  { text: 'Foreign aid and domestic priorities need better balance.', category: 'Politics' },
  { text: 'All elections should have stronger public funding and spending limits.', category: 'Politics' },
  { text: 'Direct democracy works better than pure representative democracy at smaller scales.', category: 'Politics' },
  { text: 'Political parties should face more internal democracy and transparency.', category: 'Politics' },
  { text: 'Local elections deserve as much media attention as national ones.', category: 'Politics' },
  { text: 'Election day should be a public holiday or more accessible.', category: 'Politics' },
  { text: 'Political campaigns should have strict spending limits.', category: 'Politics' },
  { text: 'Judges should be appointed through more transparent and less partisan processes.', category: 'Politics' },
  { text: 'Gerrymandering / delimitation should be handled by independent commissions.', category: 'Politics' },
  { text: 'Citizens should be able to recall elected officials more easily.', category: 'Politics' },
  { text: 'Public trust in government is lower today mostly because of transparency failures, not only policy failures.', category: 'Politics' },
  { text: 'Civic education should be mandatory before high school graduation.', category: 'Politics' },
  { text: 'Political debates should be moderated more fairly and with less bias.', category: 'Politics' },
  { text: 'Whistleblowers deserve stronger legal protection than they currently get.', category: 'Politics' },
  { text: 'Government budgets should be easier for the average citizen to understand.', category: 'Politics' },
  { text: 'Local government has more influence on daily life than most people realize.', category: 'Politics' },
  { text: 'Term limits or clearer accountability for unelected advisors would improve governance.', category: 'Politics' },
  { text: 'Online voting would increase turnout but the security risks are still significant.', category: 'Politics' },
  { text: 'Public officials should be required to hold regular town halls or public interactions.', category: 'Politics' },
  { text: 'Referendums and public consultations should be used more often for major issues.', category: 'Politics' },
  { text: 'Campaign donations should be capped regardless of the source.', category: 'Politics' },
  { text: 'Government transparency laws should apply equally across branches and levels.', category: 'Politics' },
  { text: 'Redistricting / delimitation should happen on a clearer and more regular schedule.', category: 'Politics' },
  { text: 'Public servants should face stronger penalties for corruption than ordinary citizens.', category: 'Politics' },
  { text: 'Losing weight using medication is not the same as losing weight through diet and exercise.', category: 'Health' },
  { text: 'Therapy and mental health support should be far more accessible and affordable.', category: 'Health' },
  { text: 'Mental health days should be treated the same as sick days.', category: 'Health' },
  { text: 'A plant-forward diet is generally healthier than a heavy meat-based one for most people.', category: 'Health' },
  { text: 'Fitness influencers do more harm than good.', category: 'Health' },
  { text: 'The eight-hour sleep rule is overrated; quality matters more than exact hours.', category: 'Health' },
  { text: 'Recreational cannabis should be legal and regulated everywhere.', category: 'Health' },
  { text: 'Health insurance should not be tied only to employment.', category: 'Health' },
  { text: 'Cosmetic procedures on minors should face much stricter rules.', category: 'Health' },
  { text: 'Energy drinks and high-caffeine products should be restricted for under-eighteens.', category: 'Health' },
  { text: 'Modern medicine sometimes over-prescribes antidepressants and similar drugs.', category: 'Health' },
  { text: 'Drinking alcohol is worse for you than moderate cannabis use in many respects.', category: 'Health' },
  { text: 'Walking ten thousand steps a day is more marketing than strict science.', category: 'Health' },
  { text: 'All packaged foods should be required to display a clear health rating.', category: 'Health' },
  { text: 'Universal healthcare access is a basic human right.', category: 'Health' },
  { text: 'Multivitamins are mostly a waste of money for healthy adults.', category: 'Health' },
  { text: 'Sleep tracking apps create more anxiety than they solve for many people.', category: 'Health' },
  { text: 'Fasting diets are more hype than solid science for most people.', category: 'Health' },
  { text: 'Cold plunges and similar trends are more placebo than proven physical benefit for many.', category: 'Health' },
  { text: 'Doctors should be required to explain treatment costs before prescribing them.', category: 'Health' },
  { text: 'Preventive care should be fully covered by every insurance or public health plan.', category: 'Health' },
  { text: 'Burnout should be treated as a medical and social condition, not just a personal failing.', category: 'Health' },
  { text: 'Sugar and ultra-processed foods should face stronger regulation like tobacco once did.', category: 'Health' },
  { text: 'Wearing sunscreen daily matters more than most people realize.', category: 'Health' },
  { text: 'Gyms often overcomplicate what it actually takes to get fit.', category: 'Health' },
  { text: 'Mental health screenings should be part of every annual health check.', category: 'Health' },
  { text: 'Fad diets do more harm than the weight they claim to help you lose.', category: 'Health' },
  { text: 'Hospitals and clinics should be required to post prices for common procedures publicly.', category: 'Health' },
  { text: 'Skipping breakfast is not as harmful as it\'s often made out to be.', category: 'Health' },
  { text: 'Telehealth appointments are just as effective as in-person visits for many concerns.', category: 'Health' },
  { text: 'Protein supplements are overused by people who don\'t actually need them.', category: 'Health' },
  { text: 'Chronic stress does more long-term damage than a poor diet in many cases.', category: 'Health' },
  { text: 'Standing desks are more marketing than meaningful health benefit for most people.', category: 'Health' },
  { text: 'Health class in school should include mental health, not just physical health.', category: 'Health' },
  { text: 'Painkiller dependency starts more often with legal prescriptions than illegal drugs.', category: 'Health' },
  { text: 'Annual physicals catch fewer problems than people assume.', category: 'Health' },
  { text: 'A four-day work week would improve public health more than many wellness programs.', category: 'Health' },
  { text: 'Elective surgery should require a mandatory waiting or cooling-off period.', category: 'Health' },
  { text: 'Air travel should be limited or taxed more heavily for frequent flyers.', category: 'Environment' },
  { text: 'Nuclear energy is one of the most realistic paths to lower emissions.', category: 'Environment' },
  { text: 'Single-use plastic packaging should be banned or heavily restricted by 2030.', category: 'Environment' },
  { text: 'Climate change is the most important issue of the next 20 years.', category: 'Environment' },
  { text: 'Cars should be restricted or discouraged in dense city centres.', category: 'Environment' },
  { text: 'Recycling, as currently practiced in many places, is less effective than people think.', category: 'Environment' },
  { text: 'Water-intensive lawns and landscaping should be restricted in drought-prone areas.', category: 'Environment' },
  { text: 'Fast fashion should face much stronger regulation.', category: 'Environment' },
  { text: 'Bottled water should be discouraged or restricted wherever safe tap water is available.', category: 'Environment' },
  { text: 'Cruise ships and high-impact tourism should face stricter environmental rules.', category: 'Environment' },
  { text: 'Owning multiple cars per household should be taxed or discouraged more strongly.', category: 'Environment' },
  { text: 'National parks and sensitive natural areas should limit private vehicle access.', category: 'Environment' },
  { text: 'Companies that pollute should be charged for the full environmental damage they cause.', category: 'Environment' },
  { text: 'Going paperless often saves more resources than recycling alone.', category: 'Environment' },
  { text: 'Meat consumption should reflect more of its environmental cost through pricing or policy.', category: 'Environment' },
  { text: 'Every new building should be required to include some form of renewable energy or efficiency measures.', category: 'Environment' },
  { text: 'Composting and organic waste separation should be mandatory in cities with collection systems.', category: 'Environment' },
  { text: 'Fast delivery culture is worse for the environment than people admit.', category: 'Environment' },
  { text: 'Golf courses and similar water-heavy amenities use more resources than they\'re often worth in dry regions.', category: 'Environment' },
  { text: 'Carbon offsets are more marketing than measurable impact in many cases.', category: 'Environment' },
  { text: 'Public transit should be affordable or free to reduce car dependency.', category: 'Environment' },
  { text: 'Zoos and aquariums can do more for conservation than critics sometimes give them credit for.', category: 'Environment' },
  { text: 'Electric vehicles are not as clean as marketed once full production and battery impact are factored in.', category: 'Environment' },
  { text: 'Every new home should be encouraged or required to include rainwater harvesting where feasible.', category: 'Environment' },
  { text: 'Reforestation and protection of existing forests matter as much as reducing emissions.', category: 'Environment' },
  { text: 'Packaging waste is a bigger problem than plastic straws ever were.', category: 'Environment' },
  { text: 'Space tourism is hard to justify given its environmental and resource cost.', category: 'Environment' },
  { text: 'Urban green spaces should be prioritized over parking lots in every new development.', category: 'Environment' },
];

/**
 * Categories belonging to a given collection ('everyday' | 'thoughtful'),
 * in a fixed display order — this is what CategoryPicker renders.
 */
export function getCategoriesForCollection(collection) {
  return CATEGORIES.filter((c) => CATEGORY_TO_COLLECTION[c] === collection);
}

/**
 * Picks a random topic within a collection, optionally narrowed further
 * by selected categories (empty = any category within the collection).
 */
export function spinTopic({ collection, selectedCategories = [] } = {}) {
  const collectionCategories = collection
    ? new Set(getCategoriesForCollection(collection))
    : null;

  const pool = TOPICS.filter((t) => {
    if (collectionCategories && !collectionCategories.has(t.category)) return false;
    if (selectedCategories.length > 0 && !selectedCategories.includes(t.category)) return false;
    return true;
  });

  const finalPool = pool.length > 0 ? pool : TOPICS; // fall back if a filter somehow empties the pool
  return finalPool[Math.floor(Math.random() * finalPool.length)];
}